# Notebook for the 1000 Runs Ensemble

In [108]:
import pandas as pd
import os
from utils.eda_utils import EDAUtils
import boto3

In [109]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [110]:
SCRIPT_DIR_PATH = os.getcwd()
ROOT_DIR_PATH = os.path.dirname(SCRIPT_DIR_PATH)
DATA_DIR_PATH = os.path.join(ROOT_DIR_PATH, "data")
MAPPING_DIR_PATH = os.path.join(DATA_DIR_PATH, "mapping")
SSP_DIR_PATH = os.path.join(DATA_DIR_PATH, "ssp")
TRAINING_DIR_PATH = os.path.join(DATA_DIR_PATH, "training")
CONFIG_DIR_PATH = os.path.join(ROOT_DIR_PATH, "config")

In [111]:
os.makedirs(SSP_DIR_PATH, exist_ok=True)

In [112]:
edau = EDAUtils()

In [113]:
run_id="9-18vs10-14"

In [114]:
SIMULATION_DIR_PATH = os.path.join(SSP_DIR_PATH, run_id)
print(SIMULATION_DIR_PATH)

c:\Users\pkane\sspla\ssp_louisiana\metamodel\data\ssp\9-18vs10-14

## Load SISEPUEDE WIDE_INPUTS_OUTPUTS

In [115]:
attr_primary_df = pd.read_csv(os.path.join(SIMULATION_DIR_PATH, "ATTRIBUTE_PRIMARY 9-18.csv"))
attr_primary_df

      primary_id  design_id  strategy_id  future_id
0         332332          4            0          0
1         402402          4         6004          0
2         402403          4         6004          1
3         402404          4         6004          2
4         402405          4         6004          3
...          ...        ...          ...        ...
2072       78078          0         6012          0
2073       79079          0         6013          0
2074       80080          0         6014          0
2075       81081          0         6015          0
2076       82082          0         6016          0

[2077 rows x 4 columns]

In [116]:
attr_primary_df = attr_primary_df[attr_primary_df["strategy_id"].isin([6004])]
attr_primary_df

      primary_id  design_id  strategy_id  future_id
1         402402          4         6004          0
2         402403          4         6004          1
3         402404          4         6004          2
4         402405          4         6004          3
5         402406          4         6004          4
...          ...        ...          ...        ...
997       403398          4         6004        996
998       403399          4         6004        997
999       403400          4         6004        998
1000      403401          4         6004        999
1001      403402          4         6004       1000

[1001 rows x 4 columns]

In [117]:
wide_inputs_outputs_df = pd.read_csv(os.path.join(SIMULATION_DIR_PATH, "sisepuede_results_IDE_2025-09-18t09;19;22.726476.csv"))
wide_inputs_outputs_df

,primary_id,region,time_period,area_agrc_crops_bevs_and_spices,area_agrc_crops_cereals,area_agrc_crops_fibers,area_agrc_crops_fruits,area_agrc_crops_herbs_and_other_perennial_crops,area_agrc_crops_nuts,area_agrc_crops_other_annual,...,yield_agrc_other_annual_tonne,yield_agrc_other_woody_perennial_tonne,yield_agrc_pulses_tonne,yield_agrc_rice_tonne,yield_agrc_sugar_cane_tonne,yield_agrc_tubers_tonne,yield_agrc_vegetables_and_vines_tonne,design_id,strategy_id,future_id
0,1001,louisiana,7,0,356696.043492,66146.621297,77.773211,76769.151304,6508.599365,1.119173e+06,...,0,1204.745945,2.243801e+06,2.446506e+07,171684.426729,153.672261,0,0,1000,0
1,1001,louisiana,8,0,355221.860914,65873.245131,77.451784,76451.873477,6481.700093,1.114548e+06,...,0,928.252899,2.294739e+06,2.312859e+07,170974.875290,153.037151,0,0,1000,0
2,1001,louisiana,9,0,353750.075712,65600.313541,77.130879,76135.111621,6454.844566,1.109930e+06,...,0,1174.618939,2.271010e+06,2.470988e+07,170266.477753,152.403075,0,0,1000,0
3,1001,louisiana,10,0,352280.764654,65327.840762,76.810514,75818.882257,6428.034184,1.105320e+06,...,0,1169.740125,2.261577e+06,2.460725e+07,169559.271068,151.770064,0,0,1000,0
4,1001,louisiana,11,0,350814.002751,65055.840705,76.490704,75503.201530,6401.270317,1.100718e+06,...,0,1164.869776,2.252161e+06,2.450479e+07,168853.291338,151.138152,0,0,1000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55849,405404,louisiana,31,0,400576.538479,67862.606480,94.798899,92803.361279,8395.070116,1.324963e+06,...,0,1155.352512,2.540459e+06,2.354681e+07,197810.788975,175.631833,0,4,6006,1000
55850,405404,louisiana,32,0,403345.490574,68301.283110,95.578140,93476.074424,8466.096654,1.334500e+06,...,0,1162.560049,2.553451e+06,2.362574e+07,199386.653492,177.024429,0,4,6006,1000
55851,405404,louisiana,33,0,405982.273125,68728.197688,96.316704,94107.258753,8532.817098,1.343489e+06,...,0,1169.676600,2.565517e+06,2.370233e+07,200895.110392,178.359470,0,4,6006,1000
55852,405404,louisiana,34,0,408514.005639,69144.587083,97.024119,94706.642930,8596.297503,1.352054e+06,...,0,1176.688661,2.576854e+06,2.377645e+07,202350.521090,179.648983,0,4,6006,1000
55853,405404,louisiana,35,0,410964.490769,69552.005199,97.708282,95282.285138,8657.401522,1.360300e+06,...,0,1183.597210,2.587631e+06,2.384823e+07,203765.294177,180.903448,0,4,6006,1000

In [118]:
wide_inputs_outputs_df['primary_id'].unique()

array([  1001,   2002,   3003, ..., 405402, 405403, 405404], shape=(1926,))

In [119]:
wide_inputs_outputs_df = wide_inputs_outputs_df[wide_inputs_outputs_df["primary_id"].isin(attr_primary_df["primary_id"].unique())]

In [120]:
wide_inputs_outputs_df['primary_id'].unique()

array([402402, 402403, 402404, 402405, 402406, 402407, 402408, 402409,
       402410, 402411, 402412, 402413, 402414, 402415, 402416, 402417,
       402418, 402419, 402420, 402422, 402423, 402424, 402425, 402426,
       402427, 402428, 402429, 402430, 402431, 402432, 402433, 402434,
       402435, 402436, 402437, 402438, 402440, 402441, 402442, 402443,
       402444, 402445, 402446, 402447, 402448, 402449, 402450, 402451,
       402452, 402453, 402454, 402455, 402456, 402457, 402458, 402459,
       402460, 402461, 402462, 402463, 402464, 402465, 402466, 402467,
       402468, 402469, 402470, 402471, 402472, 402473, 402474, 402475,
       402476, 402477, 402478, 402479, 402480, 402481, 402482, 402483,
       402484, 402485, 402486, 402487, 402488, 402489, 402491, 402492,
       402493, 402494, 402495, 402496, 402497, 402498, 402499, 402500,
       402501, 402502, 402503, 402504, 402505, 402506, 402507, 402508,
       402509, 402510, 402511, 402512, 402513, 402514, 402515, 402516,
       402517, 402518, 402519, 402520, 402521, 402522, 402523, 402524,
       402525, 402526, 402527, 402528, 402529, 402530, 402531, 402532,
       402534, 402535, 402536, 402537, 402538, 402539, 402540, 402541,
       402542, 402543, 402544, 402545, 402546, 402547, 402548, 402549,
       402550, 402551, 402553, 402554, 402555, 402556, 402557, 402558,
       402559, 402560, 402561, 402562, 402563, 402564, 402565, 402566,
       402567, 402568, 402569, 402570, 402571, 402572, 402573, 402574,
       402575, 402576, 402577, 402578, 402579, 402580, 402581, 402582,
       402583, 402584, 402585, 402586, 402587, 402588, 402589, 402590,
       402591, 402592, 402593, 402594, 402595, 402596, 402597, 402598,
       402599, 402600, 402601, 402602, 402603, 402604, 402606, 402607,
       402608, 402609, 402610, 402611, 402612, 402613, 402614, 402615,
       402616, 402617, 402618, 402619, 402620, 402621, 402622, 402623,
       402624, 402625, 402626, 402627, 402628, 402629, 402630, 402631,
       402632, 402633, 402634, 402635, 402636, 402637, 402638, 402639,
       402640, 402641, 402642, 402643, 402644, 402645, 402646, 402647,
       402648, 402650, 402651, 402652, 402653, 402654, 402655, 402656,
       402657, 402658, 402659, 402660, 402661, 402662, 402663, 402664,
       402665, 402666, 402667, 402668, 402669, 402670, 402671, 402672,
       402673, 402674, 402675, 402676, 402677, 402678, 402679, 402680,
       402681, 402682, 402683, 402684, 402685, 402686, 402687, 402688,
       402689, 402690, 402691, 402693, 402694, 402695, 402696, 402697,
       402699, 402700, 402701, 402702, 402703, 402704, 402705, 402706,
       402708, 402709, 402710, 402711, 402712, 402713, 402714, 402715,
       402716, 402718, 402719, 402720, 402721, 402722, 402723, 402724,
       402725, 402726, 402727, 402728, 402729, 402731, 402732, 402733,
       402734, 402735, 402736, 402737, 402738, 402739, 402740, 402741,
       402742, 402743, 402744, 402745, 402747, 402748, 402749, 402751,
       402752, 402753, 402754, 402755, 402756, 402757, 402758, 402759,
       402760, 402761, 402763, 402764, 402765, 402766, 402767, 402768,
       402769, 402770, 402771, 402772, 402773, 402774, 402775, 402776,
       402777, 402778, 402779, 402780, 402781, 402782, 402783, 402784,
       402785, 402786, 402787, 402788, 402789, 402790, 402791, 402792,
       402793, 402794, 402795, 402796, 402797, 402798, 402799, 402800,
       402801, 402802, 402803, 402804, 402805, 402806, 402807, 402808,
       402809, 402810, 402811, 402812, 402813, 402814, 402815, 402816,
       402817, 402818, 402819, 402820, 402821, 402822, 402823, 402824,
       402825, 402826, 402827, 402828, 402829, 402830, 402831, 402832,
       402833, 402834, 402835, 402836, 402837, 402838, 402839, 402840,
       402841, 402842, 402843, 402844, 402845, 402846, 402847, 402848,
       402849, 402850, 402851, 402852, 402853, 402854, 402855, 402856,
       402857, 402859, 402860, 402861, 402862, 402863, 402864, 402865,
       402866, 402867, 402868, 402869, 402870, 402871, 402872, 402873,
       402874, 402875, 402876, 402877, 402878, 402879, 402880, 402881,
       402882, 402884, 402885, 402886, 402887, 402888, 402889, 402890,
       402891, 402892, 402893, 402894, 402895, 402896, 402897, 402898,
       402899, 402900, 402901, 402902, 402903, 402904, 402905, 402906,
       402909, 402910, 402911, 402912, 402913, 402914, 402915, 402916,
       402917, 402918, 402919, 402920, 402921, 402922, 402924, 402925,
       402926, 402927, 402928, 402929, 402930, 402931, 402932, 402933,
       402934, 402935, 402936, 402937, 402938, 402939, 402940, 402941,
       402942, 402943, 402944, 402945, 402946, 402947, 402948, 402949,
       402950, 402951, 402953, 402954, 402955, 402956, 402957, 402958,
       402959, 402960, 402961, 402963, 402964, 402965, 402967, 402968,
       402969, 402970, 402971, 402972, 402973, 402974, 402975, 402976,
       402977, 402978, 402979, 402980, 402981, 402982, 402983, 402984,
       402985, 402987, 402988, 402989, 402991, 402992, 402993, 402994,
       402995, 402996, 402997, 402998, 402999, 403000, 403001, 403002,
       403003, 403004, 403005, 403006, 403007, 403008, 403009, 403010,
       403011, 403012, 403013, 403014, 403015, 403016, 403017, 403018,
       403019, 403020, 403021, 403022, 403023, 403024, 403025, 403026,
       403027, 403028, 403029, 403030, 403032, 403033, 403034, 403035,
       403036, 403037, 403038, 403039, 403040, 403041, 403042, 403043,
       403044, 403045, 403046, 403047, 403048, 403049, 403050, 403051,
       403052, 403053, 403054, 403055, 403056, 403057, 403058, 403059,
       403060, 403061, 403062, 403063, 403064, 403065, 403066, 403067,
       403068, 403069, 403070, 403071, 403072, 403073, 403074, 403075,
       403076, 403077, 403079, 403080, 403081, 403082, 403083, 403084,
       403085, 403086, 403087, 403088, 403089, 403090, 403091, 403092,
       403093, 403094, 403095, 403096, 403097, 403098, 403099, 403100,
       403101, 403102, 403103, 403104, 403105, 403106, 403107, 403108,
       403109, 403110, 403111, 403112, 403113, 403114, 403115, 403116,
       403117, 403118, 403119, 403120, 403121, 403122, 403123, 403124,
       403125, 403126, 403127, 403128, 403130, 403131, 403132, 403133,
       403134, 403135, 403136, 403137, 403138, 403139, 403140, 403141,
       403142, 403143, 403145, 403146, 403147, 403148, 403149, 403150,
       403151, 403152, 403153, 403154, 403155, 403156, 403157, 403158,
       403159, 403160, 403161, 403162, 403163, 403164, 403166, 403167,
       403168, 403169, 403170, 403171, 403172, 403173, 403174, 403175,
       403176, 403177, 403178, 403179, 403180, 403181, 403182, 403183,
       403184, 403185, 403186, 403187, 403188, 403189, 403190, 403191,
       403192, 403193, 403194, 403195, 403196, 403197, 403198, 403199,
       403200, 403201, 403202, 403203, 403204, 403205, 403206, 403207,
       403208, 403209, 403210, 403211, 403212, 403213, 403214, 403215,
       403216, 403217, 403218, 403219, 403220, 403221, 403222, 403223,
       403224, 403225, 403226, 403228, 403229, 403230, 403231, 403232,
       403233, 403234, 403235, 403236, 403237, 403238, 403239, 403240,
       403241, 403242, 403243, 403244, 403245, 403246, 403247, 403248,
       403249, 403250, 403251, 403252, 403253, 403254, 403255, 403256,
       403257, 403258, 403259, 403260, 403261, 403262, 403263, 403264,
       403265, 403266, 403267, 403269, 403271, 403272, 403273, 403274,
       403275, 403276, 403277, 403278, 403279, 403280, 403281, 403282,
       403283, 403284, 403285, 403286, 403287, 403288, 403289, 403290,
       403291, 403292, 403293, 403294, 403295, 403296, 403298, 403299,
       403300, 403301, 403302, 403303, 403304, 403305, 403306, 403307,
       403308, 403309, 403310, 403311, 403312, 403313, 403314, 403315,
       403316, 403317, 403319, 403320, 403321, 403322, 403323, 403324,
       403325, 403326, 403327, 403329, 403330, 403331, 403332, 403333,
       403334, 403335, 403336, 403338, 403339, 403340, 403341, 403342,
       403343, 403344, 403345, 403346, 403347, 403348, 403349, 403350,
       403351, 403352, 403353, 403354, 403355, 403356, 403357, 403358,
       403359, 403360, 403361, 403362, 403363, 403364, 403365, 403366,
       403367, 403368, 403369, 403370, 403371, 403372, 403373, 403374,
       403375, 403376, 403377, 403378, 403379, 403380, 403381, 403382,
       403383, 403384, 403385, 403386, 403387, 403388, 403389, 403390,
       403391, 403392, 403393, 403394, 403395, 403396, 403397, 403398,
       403399, 403400, 403401, 403402])

In [121]:
wide_inputs_outputs_df.primary_id.nunique()

964

### Production Data

In [122]:
# 2) Define your fuels and sectors
relevant_fuels = ['biomass', 
                    'coal', 
                    'coke', 
                    'diesel', 
                    'electricity',
                    'furnace_gas',
                    'gasoline', 
                    'hydrocarbon_gas_liquids',
                    'hydrogen',
                    'kerosene',
                    'natural_gas',
                    'natural_gas_liquid',
                    'oil']

sectors = ['agriculture_and_livestock',
           'cement',
           'chemicals',
           'electronics',
           'glass',
           'lime_and_carbonite',
           'metals',
           'mining',
           'other_product_manufacturing',
           'paper',
           'plastic',
           'recycled_glass',
           'recycled_metals',
           'recycled_paper',
           'recycled_plastic',
           'recycled_rubber_and_leather',
           'recycled_textiles',
           'recycled_wood',
           'rubber_and_leather',
           'textiles',
           'wood']

In [123]:
# 4) Industrial cost parameters
capex_industrial_electricity = 92666.6 * 21
capex_industrial_other       = 92666.6 * 12
opex_industrial_electricity  = 92666.6 * 2.5
opex_industrial_other        = 92666.6 * 4.5
capex_multiplier_efficiency = 10000000
opex_multiplier_efficiency = 0

In [124]:
# 5) Loop over fuels and sectors
# Use the original dataframe directly
# Initialize results dataframe
ind_fuel_demand_by_sector = pd.DataFrame({
    'primary_id': wide_inputs_outputs_df['primary_id'],
    'time_period': wide_inputs_outputs_df['time_period']
}, index=wide_inputs_outputs_df.index)

# Helper alias for tricky fuel names
alias = {
    'natural_gas_liquid': ['natural_gas_liquid', 'natural_gas_liquids'],
    'biomass': ['biomass', 'solid_biomass'],   # <-- added
}

for fuel in relevant_fuels:
    fuel_keys = alias.get(fuel, [fuel])  # use aliases everywhere for this fuel

    # ------------------------------------------------------------
    # ENTc (fuel-only) — handled OUTSIDE sector loop
    # ------------------------------------------------------------
    entc_found_col = None
    for k in fuel_keys:
        cand = f'energy_demand_enfu_subsector_total_pj_entc_fuel_{k}'
        if cand in wide_inputs_outputs_df.columns:
            entc_found_col = cand
            break
    if entc_found_col is not None:
        ind_fuel_demand_by_sector[entc_found_col] = wide_inputs_outputs_df[entc_found_col]

    # ------------------------------------------------------------
    # Efficiency column (accept any alias)
    # ------------------------------------------------------------
    eff_cols = [
        c for c in wide_inputs_outputs_df.columns
        if any(c.startswith(f'efficfactor_enfu_industrial_energy_fuel_{k}') for k in fuel_keys)
    ]
    if not eff_cols:
        continue
    fuel_efficiency = wide_inputs_outputs_df[eff_cols[0]]

    # ------------------------------------------------------------
    # Sector loop (unchanged logic; now alias-aware for fractions)
    # ------------------------------------------------------------
    for sector in sectors:
        sector_dem_cols = [c for c in wide_inputs_outputs_df.columns
                           if f'energy_demand_inen_{sector}' in c]
        sector_fuel_fraction_cols = [
            c for c in wide_inputs_outputs_df.columns
            if any(f'frac_inen_energy_{sector}_{k}' in c for k in fuel_keys)
        ]

        if sector_dem_cols and sector_fuel_fraction_cols:
            sector_total_demand = wide_inputs_outputs_df[sector_dem_cols[0]]
            sector_fuel_fraction = wide_inputs_outputs_df[sector_fuel_fraction_cols[0]]

            has_any_demand = ((sector_fuel_fraction * sector_total_demand).fillna(0) != 0).any()
            if has_any_demand or fuel == 'electricity':
                sector_fuel_demand = sector_fuel_fraction * sector_total_demand
                ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand

                # CAPEX/OPEX
                if fuel == 'electricity':
                    ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
                        sector_fuel_demand * capex_industrial_electricity
                    )
                    ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
                        sector_fuel_demand * opex_industrial_electricity
                    )
                else:
                    ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
                        sector_fuel_demand * capex_industrial_other
                    )
                    ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
                        sector_fuel_demand * opex_industrial_other
                    )

                # Fuel consumed + deltas
                sector_fuel_consumed = sector_fuel_demand / fuel_efficiency
                sector_fuel_consumed_baseline = (
                    sector_fuel_consumed.groupby(wide_inputs_outputs_df['primary_id']).transform('first')
                )
                sector_change_in_fuel_consumed = sector_fuel_consumed_baseline - sector_fuel_consumed
                ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
                ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
                    sector_change_in_fuel_consumed * capex_multiplier_efficiency
                )
                ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
                    sector_change_in_fuel_consumed * opex_multiplier_efficiency
                )

C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:87: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:87: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:87: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:87: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[entc_found_col] = wide_inputs_outputs_df[entc_found_col]
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:87: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:87: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:87: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2925024214.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed

In [125]:
ind_fuel_demand_by_sector

,primary_id,time_period,energy_demand_enfu_subsector_total_pj_entc_fuel_biomass,energy_demand_cement_biomass,energy_demand_capex_cement_biomass,energy_demand_opex_cement_biomass,efficiency_energy_saving_cement_biomass,efficiency_capex_cement_biomass,efficiency_opex_cement_biomass,energy_demand_chemicals_biomass,...,energy_demand_opex_other_product_manufacturing_oil,efficiency_energy_saving_other_product_manufacturing_oil,efficiency_capex_other_product_manufacturing_oil,efficiency_opex_other_product_manufacturing_oil,energy_demand_recycled_wood_oil,energy_demand_capex_recycled_wood_oil,energy_demand_opex_recycled_wood_oil,efficiency_energy_saving_recycled_wood_oil,efficiency_capex_recycled_wood_oil,efficiency_opex_recycled_wood_oil
2146,402402,7,62.971982,6.245842,6.945372e+06,2.604514e+06,0.000000,0.000000e+00,0.0,0.000361,...,1.065403e+07,0.000000,0.000000e+00,0.0,0.319755,355567.121778,133337.670667,0.000000,0.000000e+00,0.0
2147,402402,8,37.778067,6.004527,6.677029e+06,2.503886e+06,0.440531,4.405308e+06,0.0,0.000337,...,1.101825e+07,-1.019247,-1.019247e+07,-0.0,0.314100,349279.179225,130979.692209,0.009181,9.181124e+04,0.0
2148,402402,9,68.355513,5.820587,6.472488e+06,2.427183e+06,0.783215,7.832155e+06,0.0,0.000302,...,1.138607e+07,-2.041192,-2.041192e+07,-0.0,0.306088,340369.779635,127638.667363,0.021401,2.140106e+05,0.0
2149,402402,10,50.996675,5.810337,6.461090e+06,2.422909e+06,0.838443,8.384430e+06,0.0,0.000267,...,1.179935e+07,-3.197407,-3.197407e+07,-0.0,0.297894,331257.757247,124221.658968,0.033769,3.376881e+05,0.0
2150,402402,11,51.070442,6.016999,6.690899e+06,2.509087e+06,0.539047,5.390472e+06,0.0,0.000236,...,1.222929e+07,-4.395974,-4.395974e+07,-0.0,0.290604,323151.473668,121181.802625,0.044862,4.486193e+05,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30097,403402,31,133.257639,6.204226,6.899094e+06,2.587160e+06,2.824968,2.824968e+07,0.0,0.000000,...,9.760938e+06,10.278636,1.027864e+08,0.0,0.051724,57516.981125,21568.867922,0.372370,3.723702e+06,0.0
30098,403402,32,133.356403,6.117863,6.803059e+06,2.551147e+06,3.015835,3.015835e+07,0.0,0.000000,...,9.486657e+06,11.172821,1.117282e+08,0.0,0.046466,51669.845870,19376.192201,0.378152,3.781519e+06,0.0
30099,403402,33,133.472882,6.026856,6.701859e+06,2.513197e+06,3.206678,3.206678e+07,0.0,0.000000,...,9.204921e+06,12.063254,1.206325e+08,0.0,0.041599,46258.202991,17346.826122,0.383424,3.834244e+06,0.0
30100,403402,34,133.611789,5.930803,6.595048e+06,2.473143e+06,3.398057,3.398057e+07,0.0,0.000000,...,8.915359e+06,12.951351,1.295135e+08,0.0,0.037098,41253.268976,15469.975866,0.388230,3.882302e+06,0.0
30101,403402,35,134.278386,5.829157,6.482018e+06,2.430757e+06,3.590677,3.590677e+07,0.0,0.000000,...,8.617399e+06,13.838947,1.383895e+08,0.0,0.032939,36628.326303,13735.622364,0.392608,3.926084e+06,0.0

In [126]:
subset= ind_fuel_demand_by_sector.filter(regex=r'^energy_demand')

In [127]:
ind_fuel_demand_by_sector.isna().sum().sum()

np.int64(0)

## Transform time series format into single-row format

### Production and Production Cost Data

In [128]:
industry_cost_vars = [
    c for c in ind_fuel_demand_by_sector.columns
    if c.startswith("energy_demand_capex_") or c.startswith("energy_demand_opex_")
]

In [129]:
industry_product_vars =  [
    c for c in ind_fuel_demand_by_sector.columns
    if c.startswith("energy_demand_")
    and "_capex_" not in c
    and "_opex_" not in c
]

In [130]:
ind_fuel_demand_by_sector[industry_cost_vars]

,energy_demand_capex_cement_biomass,energy_demand_opex_cement_biomass,energy_demand_capex_chemicals_biomass,energy_demand_opex_chemicals_biomass,energy_demand_capex_electronics_biomass,energy_demand_opex_electronics_biomass,energy_demand_capex_lime_and_carbonite_biomass,energy_demand_opex_lime_and_carbonite_biomass,energy_demand_capex_mining_biomass,energy_demand_opex_mining_biomass,...,energy_demand_capex_electronics_oil,energy_demand_opex_electronics_oil,energy_demand_capex_lime_and_carbonite_oil,energy_demand_opex_lime_and_carbonite_oil,energy_demand_capex_mining_oil,energy_demand_opex_mining_oil,energy_demand_capex_other_product_manufacturing_oil,energy_demand_opex_other_product_manufacturing_oil,energy_demand_capex_recycled_wood_oil,energy_demand_opex_recycled_wood_oil
2146,6.945372e+06,2.604514e+06,400.946233,150.354838,26.176471,9.816177,0.000000,0.000000,622.277639,233.354115,...,1694.069129,635.275924,0.000000,0.000000,12954.468460,4857.925672,2.841075e+07,1.065403e+07,355567.121778,133337.670667
2147,6.677029e+06,2.503886e+06,374.336101,140.376038,29.894930,11.210599,0.000000,0.000000,662.073791,248.277672,...,1790.850816,671.569056,0.000000,0.000000,12061.561422,4523.085533,2.938199e+07,1.101825e+07,349279.179225,130979.692209
2148,6.472488e+06,2.427183e+06,336.057998,126.021749,32.168282,12.063106,0.000000,0.000000,703.506705,263.815014,...,1830.345443,686.379541,0.000000,0.000000,11109.988295,4166.245611,3.036286e+07,1.138607e+07,340369.779635,127638.667363
2149,6.461090e+06,2.422909e+06,297.042592,111.390972,34.209176,12.828441,0.000000,0.000000,744.199705,279.074889,...,1900.179145,712.567179,0.000000,0.000000,10088.438813,3783.164555,3.146494e+07,1.179935e+07,331257.757247,124221.658968
2150,6.690899e+06,2.509087e+06,262.555493,98.458310,36.099622,13.537358,0.000000,0.000000,783.495522,293.810821,...,1988.692454,745.759670,0.000000,0.000000,9001.151673,3375.431877,3.261144e+07,1.222929e+07,323151.473668,121181.802625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30097,6.899094e+06,2.587160e+06,0.000000,0.000000,55.579344,20.842254,172791.611833,64796.854437,630.206454,236.327420,...,2579.986185,967.494819,274786.972929,103045.114848,0.000000,0.000000,2.602917e+07,9.760938e+06,57516.981125,21568.867922
30098,6.803059e+06,2.551147e+06,0.000000,0.000000,54.744874,20.529328,165040.026163,61890.009811,611.494427,229.310410,...,2525.211972,946.954490,260530.897523,97699.086571,0.000000,0.000000,2.529775e+07,9.486657e+06,51669.845870,19376.192201
30099,6.701859e+06,2.513197e+06,0.000000,0.000000,53.850140,20.193803,157195.850413,58948.443905,592.106616,222.039981,...,2468.804057,925.801521,246406.627950,92402.485481,0.000000,0.000000,2.454646e+07,9.204921e+06,46258.202991,17346.826122
30100,6.595048e+06,2.473143e+06,0.000000,0.000000,52.888897,19.833336,149283.324927,55981.246848,572.028554,214.510708,...,2410.458918,903.922094,232438.588102,87164.470538,0.000000,0.000000,2.377429e+07,8.915359e+06,41253.268976,15469.975866
30101,6.482018e+06,2.430757e+06,0.000000,0.000000,51.853512,19.445067,141326.899096,52997.587161,551.239850,206.714944,...,2349.818396,881.181898,218650.273218,81993.852457,0.000000,0.000000,2.297973e+07,8.617399e+06,36628.326303,13735.622364

In [131]:
ind_fuel_demand_by_sector[industry_product_vars]

,energy_demand_enfu_subsector_total_pj_entc_fuel_biomass,energy_demand_cement_biomass,energy_demand_chemicals_biomass,energy_demand_electronics_biomass,energy_demand_lime_and_carbonite_biomass,energy_demand_mining_biomass,energy_demand_other_product_manufacturing_biomass,energy_demand_paper_biomass,energy_demand_recycled_wood_biomass,energy_demand_enfu_subsector_total_pj_entc_fuel_coal,...,energy_demand_textiles_natural_gas,energy_demand_enfu_subsector_total_pj_entc_fuel_natural_gas_liquid,energy_demand_enfu_subsector_total_pj_entc_fuel_oil,energy_demand_cement_oil,energy_demand_chemicals_oil,energy_demand_electronics_oil,energy_demand_lime_and_carbonite_oil,energy_demand_mining_oil,energy_demand_other_product_manufacturing_oil,energy_demand_recycled_wood_oil
2146,62.971982,6.245842,0.000361,0.000024,0.000000,0.000560,17.498970,23.556011,6.212763,0,...,0.061508,20754.050391,0,12.726039,0.010728,0.001523,0.000000,0.011650,25.549257,0.319755
2147,37.778067,6.004527,0.000337,0.000027,0.000000,0.000595,17.775718,23.111262,6.459065,0,...,0.063520,15891.500001,0,13.489543,0.010654,0.001610,0.000000,0.010847,26.422671,0.314100
2148,68.355513,5.820587,0.000302,0.000029,0.000000,0.000633,17.873296,22.694150,6.667850,0,...,0.066175,19128.382489,0,12.966827,0.010629,0.001646,0.000000,0.009991,27.304749,0.306088
2149,50.996675,5.810337,0.000267,0.000031,0.000000,0.000669,17.918414,22.151676,6.853172,0,...,0.068386,19114.298149,0,12.342857,0.010597,0.001709,0.000000,0.009072,28.295832,0.297894
2150,51.070442,6.016999,0.000236,0.000032,0.000000,0.000705,17.960140,21.505832,7.028890,0,...,0.071145,19205.943280,0,12.182521,0.010575,0.001788,0.000000,0.008095,29.326858,0.290604
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30097,133.257639,6.204226,0.000000,0.000050,0.155388,0.000567,8.689779,1.846829,3.345148,0,...,0.106250,32665.220426,0,9.866454,0.006147,0.002320,0.247111,0.000000,23.407543,0.051724
30098,133.356403,6.117863,0.000000,0.000049,0.148417,0.000550,8.295357,1.198543,3.190400,0,...,0.105365,33403.434269,0,9.657611,0.005965,0.002271,0.234291,0.000000,22.749793,0.046466
30099,133.472882,6.026856,0.000000,0.000048,0.141363,0.000532,7.910112,0.581256,3.038084,0,...,0.104397,34179.730325,0,9.447178,0.005786,0.002220,0.221589,0.000000,22.074167,0.041599
30100,133.611789,5.930803,0.000000,0.000048,0.134248,0.000514,7.533017,0.000000,2.887884,0,...,0.103326,34995.921031,0,9.234436,0.005609,0.002168,0.209028,0.000000,21.379774,0.037098
30101,134.278386,5.829157,0.000000,0.000047,0.127093,0.000496,7.162953,0.000000,2.739444,0,...,0.102124,35847.965474,0,9.018430,0.005434,0.002113,0.196628,0.000000,20.665239,0.032939

#### production cost

In [132]:
# Sum all the subsector emission columns across axis=1
la_production_cost_total_df = ind_fuel_demand_by_sector.copy()
la_production_cost_total_df["production_cost_total"] = la_production_cost_total_df[industry_cost_vars].sum(axis=1)

# Show only the inputs that went into the sum + the result
la_production_cost_total_df[industry_cost_vars + ["production_cost_total"]].head()

,energy_demand_capex_cement_biomass,energy_demand_opex_cement_biomass,energy_demand_capex_chemicals_biomass,energy_demand_opex_chemicals_biomass,energy_demand_capex_electronics_biomass,energy_demand_opex_electronics_biomass,energy_demand_capex_lime_and_carbonite_biomass,energy_demand_opex_lime_and_carbonite_biomass,energy_demand_capex_mining_biomass,energy_demand_opex_mining_biomass,...,energy_demand_opex_electronics_oil,energy_demand_capex_lime_and_carbonite_oil,energy_demand_opex_lime_and_carbonite_oil,energy_demand_capex_mining_oil,energy_demand_opex_mining_oil,energy_demand_capex_other_product_manufacturing_oil,energy_demand_opex_other_product_manufacturing_oil,energy_demand_capex_recycled_wood_oil,energy_demand_opex_recycled_wood_oil,production_cost_total
2146,6.945372e+06,2.604514e+06,400.946233,150.354838,26.176471,9.816177,0.0,0.0,622.277639,233.354115,...,635.275924,0.0,0.0,12954.468460,4857.925672,2.841075e+07,1.065403e+07,355567.121778,133337.670667,5.439966e+08
2147,6.677029e+06,2.503886e+06,374.336101,140.376038,29.894930,11.210599,0.0,0.0,662.073791,248.277672,...,671.569056,0.0,0.0,12061.561422,4523.085533,2.938199e+07,1.101825e+07,349279.179225,130979.692209,5.388151e+08
2148,6.472488e+06,2.427183e+06,336.057998,126.021749,32.168282,12.063106,0.0,0.0,703.506705,263.815014,...,686.379541,0.0,0.0,11109.988295,4166.245611,3.036286e+07,1.138607e+07,340369.779635,127638.667363,5.340934e+08
2149,6.461090e+06,2.422909e+06,297.042592,111.390972,34.209176,12.828441,0.0,0.0,744.199705,279.074889,...,712.567179,0.0,0.0,10088.438813,3783.164555,3.146494e+07,1.179935e+07,331257.757247,124221.658968,5.303032e+08
2150,6.690899e+06,2.509087e+06,262.555493,98.458310,36.099622,13.537358,0.0,0.0,783.495522,293.810821,...,745.759670,0.0,0.0,9001.151673,3375.431877,3.261144e+07,1.222929e+07,323151.473668,121181.802625,5.270936e+08

In [133]:
# Keep only the primary_id, time_period, and emission_total columns
la_production_cost_total_df = la_production_cost_total_df[["primary_id", "time_period", "production_cost_total"]]
la_production_cost_total_df.head()

      primary_id  time_period  production_cost_total
2146      402402            7           5.439966e+08
2147      402402            8           5.388151e+08
2148      402402            9           5.340934e+08
2149      402402           10           5.303032e+08
2150      402402           11           5.270936e+08

In [134]:
# aggregate data by primary_id summing the emissions
la_production_cost_df_mean_agg = la_production_cost_total_df.groupby(["primary_id"]).mean().reset_index()

# Drop time period column
la_production_cost_df_mean_agg = la_production_cost_df_mean_agg.drop(columns=["time_period"])
la_production_cost_df_mean_agg.head()

   primary_id  production_cost_total
0      402402           4.963916e+08
1      402403           5.295847e+08
2      402404           5.324490e+08
3      402405           5.151575e+08
4      402406           5.353014e+08

In [135]:
la_production_cost_df_mean_agg.shape

(964, 2)

#### production

In [136]:
# columns: base energy demand only (no capex/opex)
industry_product_vars = [
    c for c in ind_fuel_demand_by_sector.columns
    if c.startswith("energy_demand_") and "_capex_" not in c and "_opex_" not in c
]

la_production_total_df = ind_fuel_demand_by_sector.copy()
la_production_total_df["production_total"] = (
    la_production_total_df[industry_product_vars].sum(axis=1, min_count=1)
)

# show only what went into the sum + the result
la_production_total_df[industry_product_vars + ["production_total"]].head()

,energy_demand_enfu_subsector_total_pj_entc_fuel_biomass,energy_demand_cement_biomass,energy_demand_chemicals_biomass,energy_demand_electronics_biomass,energy_demand_lime_and_carbonite_biomass,energy_demand_mining_biomass,energy_demand_other_product_manufacturing_biomass,energy_demand_paper_biomass,energy_demand_recycled_wood_biomass,energy_demand_enfu_subsector_total_pj_entc_fuel_coal,...,energy_demand_enfu_subsector_total_pj_entc_fuel_natural_gas_liquid,energy_demand_enfu_subsector_total_pj_entc_fuel_oil,energy_demand_cement_oil,energy_demand_chemicals_oil,energy_demand_electronics_oil,energy_demand_lime_and_carbonite_oil,energy_demand_mining_oil,energy_demand_other_product_manufacturing_oil,energy_demand_recycled_wood_oil,production_total
2146,62.971982,6.245842,0.000361,0.000024,0.0,0.000560,17.498970,23.556011,6.212763,0,...,20754.050391,0,12.726039,0.010728,0.001523,0.0,0.011650,25.549257,0.319755,36790.727355
2147,37.778067,6.004527,0.000337,0.000027,0.0,0.000595,17.775718,23.111262,6.459065,0,...,15891.500001,0,13.489543,0.010654,0.001610,0.0,0.010847,26.422671,0.314100,31702.637359
2148,68.355513,5.820587,0.000302,0.000029,0.0,0.000633,17.873296,22.694150,6.667850,0,...,19128.382489,0,12.966827,0.010629,0.001646,0.0,0.009991,27.304749,0.306088,34775.052766
2149,50.996675,5.810337,0.000267,0.000031,0.0,0.000669,17.918414,22.151676,6.853172,0,...,19114.298149,0,12.342857,0.010597,0.001709,0.0,0.009072,28.295832,0.297894,34779.974132
2150,51.070442,6.016999,0.000236,0.000032,0.0,0.000705,17.960140,21.505832,7.028890,0,...,19205.943280,0,12.182521,0.010575,0.001788,0.0,0.008095,29.326858,0.290604,34839.467339

In [137]:
# Keep only the primary_id, time_period, and emission_total columns
la_production_total_df = la_production_total_df[["primary_id", "time_period", "production_total"]]
la_production_total_df.head()

      primary_id  time_period  production_total
2146      402402            7      36790.727355
2147      402402            8      31702.637359
2148      402402            9      34775.052766
2149      402402           10      34779.974132
2150      402402           11      34839.467339

In [138]:
# aggregate data by primary_id summing the emissions
la_production_df_mean_agg = la_production_total_df.groupby(["primary_id"]).mean().reset_index()

# Drop time period column
la_production_df_mean_agg = la_production_df_mean_agg.drop(columns=["time_period"])
la_production_df_mean_agg.head()

   primary_id  production_total
0      402402      45276.649936
1      402403      41769.235709
2      402404      46583.187775
3      402405      43117.173433
4      402406      51385.756210

In [139]:
ind_fuel_demand_by_sector_9_18 = ind_fuel_demand_by_sector
la_production_cost_total_df_9_18 = la_production_cost_total_df
la_production_cost_df_mean_agg_9_18 = la_production_cost_df_mean_agg
la_production_df_mean_agg_9_18 = la_production_df_mean_agg
la_production_total_df_9_18 = la_production_total_df

In [140]:
del(ind_fuel_demand_by_sector,
la_production_cost_total_df,
la_production_cost_df_mean_agg, 
la_production_df_mean_agg,
la_production_total_df)

## Load SISEPUEDE WIDE_INPUTS_OUTPUTS

In [141]:
attr_primary_df = pd.read_csv(os.path.join(SIMULATION_DIR_PATH, "ATTRIBUTE_PRIMARY 10-14.csv"))
attr_primary_df

      primary_id  design_id  strategy_id  future_id
0         368368          4            0          0
1         438438          4         6004          0
2         438439          4         6004          1
3         438440          4         6004          2
4         438441          4         6004          3
...          ...        ...          ...        ...
997       439434          4         6004        996
998       439435          4         6004        997
999       439436          4         6004        998
1000      439437          4         6004        999
1001      439438          4         6004       1000

[1002 rows x 4 columns]

In [142]:
attr_primary_df = attr_primary_df[attr_primary_df["strategy_id"].isin([6004])]
attr_primary_df

      primary_id  design_id  strategy_id  future_id
1         438438          4         6004          0
2         438439          4         6004          1
3         438440          4         6004          2
4         438441          4         6004          3
5         438442          4         6004          4
...          ...        ...          ...        ...
997       439434          4         6004        996
998       439435          4         6004        997
999       439436          4         6004        998
1000      439437          4         6004        999
1001      439438          4         6004       1000

[1001 rows x 4 columns]

In [143]:
wide_inputs_outputs_df = pd.read_csv(os.path.join(SIMULATION_DIR_PATH, "sisepuede_results_IDE_2025-10-14t00;19;25.886881_cleaned.csv"))
wide_inputs_outputs_df

,primary_id,region,time_period,area_agrc_crops_bevs_and_spices,area_agrc_crops_cereals,area_agrc_crops_fibers,area_agrc_crops_fruits,area_agrc_crops_herbs_and_other_perennial_crops,area_agrc_crops_nuts,area_agrc_crops_other_annual,...,emission_co2e_subsector_total_inen,emission_co2e_subsector_total_ippu,emission_co2e_subsector_total_lndu,emission_co2e_subsector_total_lsmm,emission_co2e_subsector_total_lvst,emission_co2e_subsector_total_scoe,emission_co2e_subsector_total_soil,emission_co2e_subsector_total_trns,emission_co2e_subsector_total_trww,emission_co2e_subsector_total_waso
0,368368,louisiana,7,0,356696.043492,66146.621297,77.773211,76769.151304,6508.599365,1.119173e+06,...,117.042622,2.885346,-0.077001,0.924671,0.845459,4.491483,1.233181,45.130223,0.447204,3.138402
1,368368,louisiana,8,0,355221.860914,65873.245131,77.451784,76451.873477,6481.700093,1.114548e+06,...,114.905242,2.893930,-0.085764,0.922202,0.832727,4.525430,1.225662,45.865290,0.454013,3.189568
2,368368,louisiana,9,0,353750.075712,65600.313541,77.130879,76135.111621,6454.844566,1.109930e+06,...,116.108554,2.904645,-0.094510,0.920094,0.820192,4.561021,1.213064,46.698636,0.461144,3.239706
3,368368,louisiana,10,0,352280.764654,65327.840762,76.810514,75818.882257,6428.034184,1.105320e+06,...,116.039398,2.917465,-0.103238,0.918245,0.807853,4.598409,1.194657,47.611029,0.468528,3.291336
4,368368,louisiana,11,0,350814.002751,65055.840705,76.490704,75503.201530,6401.270317,1.100718e+06,...,116.143155,2.932343,-0.111948,0.916637,0.795706,4.637659,1.170317,48.587463,0.476114,3.343789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29053,439438,louisiana,31,0,394099.600570,66907.447597,96.502416,91156.969998,8536.698966,1.354004e+06,...,55.781309,2.467431,-0.828532,0.537670,0.713817,3.987120,1.815144,27.730195,0.519819,7.109860
29054,439438,louisiana,32,0,397151.340963,67357.976820,97.689091,91932.200996,8646.210808,1.369353e+06,...,53.971814,2.422463,-0.886190,0.511884,0.697888,3.974305,1.835858,27.181664,0.522400,7.315643
29055,439438,louisiana,33,0,400055.592031,67801.160115,98.824247,92655.158178,8749.992059,1.384002e+06,...,52.227981,2.377047,-0.942069,0.485924,0.680952,3.963841,1.866267,26.657231,0.525030,7.522671
29056,439438,louisiana,34,0,402829.889014,68236.081895,99.915282,93333.892444,8848.955183,1.398046e+06,...,50.539069,2.331070,-0.991002,0.459920,0.663174,3.955552,1.874873,26.153741,0.527707,7.730972
29057,439438,louisiana,35,0,405493.197943,68662.630054,100.969684,93976.210335,8943.983531,1.411583e+06,...,48.366063,2.284396,-1.001408,0.433987,0.644709,3.949323,1.876416,25.667608,0.530422,7.940522

In [144]:
wide_inputs_outputs_df['primary_id'].unique()

array([368368, 438438, 438439, ..., 439436, 439437, 439438], shape=(1002,))

In [145]:
wide_inputs_outputs_df = wide_inputs_outputs_df[wide_inputs_outputs_df["primary_id"].isin(attr_primary_df["primary_id"].unique())]

In [146]:
wide_inputs_outputs_df['primary_id'].unique()

array([438438, 438439, 438440, ..., 439436, 439437, 439438], shape=(1001,))

In [147]:
wide_inputs_outputs_df.primary_id.nunique()

1001

In [148]:
# 2) Define your fuels and sectors
relevant_fuels = ['biomass', 
                    'coal', 
                    'coke', 
                    'diesel', 
                    'electricity',
                    'furnace_gas',
                    'gasoline', 
                    'hydrocarbon_gas_liquids',
                    'hydrogen',
                    'kerosene',
                    'natural_gas',
                    'natural_gas_liquid',
                    'oil']

sectors = ['agriculture_and_livestock',
           'cement',
           'chemicals',
           'electronics',
           'glass',
           'lime_and_carbonite',
           'metals',
           'mining',
           'other_product_manufacturing',
           'paper',
           'plastic',
           'recycled_glass',
           'recycled_metals',
           'recycled_paper',
           'recycled_plastic',
           'recycled_rubber_and_leather',
           'recycled_textiles',
           'recycled_wood',
           'rubber_and_leather',
           'textiles',
           'wood']

In [149]:
# 4) Industrial cost parameters
capex_industrial_electricity = 92666.6 * 21
capex_industrial_other       = 92666.6 * 12
opex_industrial_electricity  = 92666.6 * 2.5
opex_industrial_other        = 92666.6 * 4.5
capex_multiplier_efficiency = 10000000
opex_multiplier_efficiency = 0

In [150]:
# 5) Loop over fuels and sectors
# Use the original dataframe directly
# Initialize results dataframe
ind_fuel_demand_by_sector = pd.DataFrame({
    'primary_id': wide_inputs_outputs_df['primary_id'],
    'time_period': wide_inputs_outputs_df['time_period']
}, index=wide_inputs_outputs_df.index)

# Helper alias for tricky fuel names
alias = {
    'natural_gas_liquid': ['natural_gas_liquid', 'natural_gas_liquids'],
    'biomass': ['biomass', 'solid_biomass'],   # <-- added
}

for fuel in relevant_fuels:
    fuel_keys = alias.get(fuel, [fuel])  # use aliases everywhere for this fuel

    # ------------------------------------------------------------
    # ENTc (fuel-only) — handled OUTSIDE sector loop
    # ------------------------------------------------------------
    entc_found_col = None
    for k in fuel_keys:
        cand = f'energy_demand_enfu_subsector_total_pj_entc_fuel_{k}'
        if cand in wide_inputs_outputs_df.columns:
            entc_found_col = cand
            break
    if entc_found_col is not None:
        ind_fuel_demand_by_sector[entc_found_col] = wide_inputs_outputs_df[entc_found_col]

    # ------------------------------------------------------------
    # Efficiency column (accept any alias)
    # ------------------------------------------------------------
    eff_cols = [
        c for c in wide_inputs_outputs_df.columns
        if any(c.startswith(f'efficfactor_enfu_industrial_energy_fuel_{k}') for k in fuel_keys)
    ]
    if not eff_cols:
        continue
    fuel_efficiency = wide_inputs_outputs_df[eff_cols[0]]

    # ------------------------------------------------------------
    # Sector loop (unchanged logic; now alias-aware for fractions)
    # ------------------------------------------------------------
    for sector in sectors:
        sector_dem_cols = [c for c in wide_inputs_outputs_df.columns
                           if f'energy_demand_inen_{sector}' in c]
        sector_fuel_fraction_cols = [
            c for c in wide_inputs_outputs_df.columns
            if any(f'frac_inen_energy_{sector}_{k}' in c for k in fuel_keys)
        ]

        if sector_dem_cols and sector_fuel_fraction_cols:
            sector_total_demand = wide_inputs_outputs_df[sector_dem_cols[0]]
            sector_fuel_fraction = wide_inputs_outputs_df[sector_fuel_fraction_cols[0]]

            has_any_demand = ((sector_fuel_fraction * sector_total_demand).fillna(0) != 0).any()
            if has_any_demand or fuel == 'electricity':
                sector_fuel_demand = sector_fuel_fraction * sector_total_demand
                ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand

                # CAPEX/OPEX
                if fuel == 'electricity':
                    ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
                        sector_fuel_demand * capex_industrial_electricity
                    )
                    ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
                        sector_fuel_demand * opex_industrial_electricity
                    )
                else:
                    ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
                        sector_fuel_demand * capex_industrial_other
                    )
                    ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
                        sector_fuel_demand * opex_industrial_other
                    )

                # Fuel consumed + deltas
                sector_fuel_consumed = sector_fuel_demand / fuel_efficiency
                sector_fuel_consumed_baseline = (
                    sector_fuel_consumed.groupby(wide_inputs_outputs_df['primary_id']).transform('first')
                )
                sector_change_in_fuel_consumed = sector_fuel_consumed_baseline - sector_fuel_consumed
                ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
                ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
                    sector_change_in_fuel_consumed * capex_multiplier_efficiency
                )
                ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
                    sector_change_in_fuel_consumed * opex_multiplier_efficiency
                )

C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:87: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:87: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:87: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[entc_found_col] = wide_inputs_outputs_df[entc_found_col]
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:87: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:87: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:87: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:87: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_{sector}_{fuel}'] = sector_fuel_demand
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_capex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'energy_demand_opex_{sector}_{fuel}'] = (
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_energy_saving_{sector}_{fuel}'] = sector_change_in_fuel_consumed
C:\Users\pkane\AppData\Local\Temp\ipykernel_19220\2033961771.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ind_fuel_demand_by_sector[f'efficiency_capex_{sector}_{fuel}'] = (

In [151]:
ind_fuel_demand_by_sector

,primary_id,time_period,energy_demand_enfu_subsector_total_pj_entc_fuel_biomass,energy_demand_agriculture_and_livestock_biomass,energy_demand_capex_agriculture_and_livestock_biomass,energy_demand_opex_agriculture_and_livestock_biomass,efficiency_energy_saving_agriculture_and_livestock_biomass,efficiency_capex_agriculture_and_livestock_biomass,efficiency_opex_agriculture_and_livestock_biomass,energy_demand_cement_biomass,...,energy_demand_opex_rubber_and_leather_oil,efficiency_energy_saving_rubber_and_leather_oil,efficiency_capex_rubber_and_leather_oil,efficiency_opex_rubber_and_leather_oil,energy_demand_wood_oil,energy_demand_capex_wood_oil,energy_demand_opex_wood_oil,efficiency_energy_saving_wood_oil,efficiency_capex_wood_oil,efficiency_opex_wood_oil
29,438438,7,36.017886,5.148130,5.724716e+06,2.146769e+06,0.000000,0.000000e+00,0.0,0.0,...,46842.027764,0.000000,0.000000e+00,0.0,1.736232,1.930689e+06,724008.208766,0.000000,0.000000e+00,0.0
30,438438,8,34.962556,4.831583,5.372716e+06,2.014769e+06,0.557609,5.576094e+06,0.0,0.0,...,48162.385908,-0.003590,-3.590101e+04,-0.0,1.690962,1.880348e+06,705130.527630,0.069119,6.911876e+05,0.0
31,438438,9,34.162696,5.188607,5.769727e+06,2.163648e+06,0.001712,1.712164e+04,0.0,0.0,...,49678.320015,-0.007767,-7.766882e+04,-0.0,1.632539,1.815382e+06,680768.281295,0.155047,1.550471e+06,0.0
32,438438,10,29.882798,5.164214,5.742602e+06,2.153476e+06,0.075964,7.596398e+05,0.0,0.0,...,50339.439286,-0.009218,-9.218061e+04,-0.0,1.573339,1.749552e+06,656082.065166,0.241342,2.413419e+06,0.0
33,438438,11,30.039144,5.139957,5.715628e+06,2.143361e+06,0.149536,1.495363e+06,0.0,0.0,...,49880.797365,-0.007146,-7.145891e+04,-0.0,1.519447,1.689624e+06,633609.070712,0.320044,3.200435e+06,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29053,439438,31,41.647113,3.172670,3.528006e+06,1.323002e+06,4.900036,4.900036e+07,0.0,0.0,...,0.000000,0.149174,1.491745e+06,0.0,0.405791,4.512397e+05,169214.891770,1.914708,1.914708e+07,0.0
29054,439438,32,42.076540,3.074047,3.418338e+06,1.281877e+06,5.060174,5.060174e+07,0.0,0.0,...,0.000000,0.149174,1.491745e+06,0.0,0.371839,4.134852e+05,155056.938066,1.951510,1.951510e+07,0.0
29055,439438,33,42.520829,2.973573,3.306611e+06,1.239979e+06,5.217509,5.217509e+07,0.0,0.0,...,0.000000,0.149174,1.491745e+06,0.0,0.339614,3.776502e+05,141618.821748,1.985786,1.985786e+07,0.0
29056,439438,34,42.980062,2.871395,3.192989e+06,1.197371e+06,5.372079,5.372079e+07,0.0,0.0,...,0.000000,0.149174,1.491745e+06,0.0,0.309066,3.436808e+05,128880.290716,2.017687,2.017687e+07,0.0
29057,439438,35,43.444108,2.767673,3.077650e+06,1.154119e+06,5.523898,5.523898e+07,0.0,0.0,...,0.000000,0.149174,1.491745e+06,0.0,0.280149,3.115254e+05,116822.030961,2.047351,2.047351e+07,0.0

In [152]:
ind_fuel_demand_by_sector.isna().sum().sum()

np.int64(0)

### Production and Production Cost Data

In [153]:
industry_cost_vars = [
    c for c in ind_fuel_demand_by_sector.columns
    if c.startswith("energy_demand_capex_") or c.startswith("energy_demand_opex_")
]

In [154]:
industry_product_vars =  [
    c for c in ind_fuel_demand_by_sector.columns
    if c.startswith("energy_demand_")
    and "_capex_" not in c
    and "_opex_" not in c
]

In [155]:
ind_fuel_demand_by_sector[industry_cost_vars]

,energy_demand_capex_agriculture_and_livestock_biomass,energy_demand_opex_agriculture_and_livestock_biomass,energy_demand_capex_cement_biomass,energy_demand_opex_cement_biomass,energy_demand_capex_chemicals_biomass,energy_demand_opex_chemicals_biomass,energy_demand_capex_electronics_biomass,energy_demand_opex_electronics_biomass,energy_demand_capex_glass_biomass,energy_demand_opex_glass_biomass,...,energy_demand_capex_plastic_oil,energy_demand_opex_plastic_oil,energy_demand_capex_recycled_metals_oil,energy_demand_opex_recycled_metals_oil,energy_demand_capex_recycled_plastic_oil,energy_demand_opex_recycled_plastic_oil,energy_demand_capex_rubber_and_leather_oil,energy_demand_opex_rubber_and_leather_oil,energy_demand_capex_wood_oil,energy_demand_opex_wood_oil
29,5.724716e+06,2.146769e+06,0.0,0.0,317965.809889,119237.178709,92.322045,34.620767,2513.271361,942.476760,...,779719.332924,292394.749847,0.0,0.0,0.0,0.0,124912.074038,46842.027764,1.930689e+06,724008.208766
30,5.372716e+06,2.014769e+06,0.0,0.0,298057.573990,111771.590246,105.837249,39.688968,2426.435685,909.913382,...,787120.223762,295170.083911,0.0,0.0,0.0,0.0,128433.029088,48162.385908,1.880348e+06,705130.527630
31,5.769727e+06,2.163648e+06,0.0,0.0,268656.188746,100746.070780,114.317824,42.869184,2362.109450,885.791044,...,797321.423344,298995.533754,0.0,0.0,0.0,0.0,132475.520039,49678.320015,1.815382e+06,680768.281295
32,5.742602e+06,2.153476e+06,0.0,0.0,238421.547821,89408.080433,122.032109,45.762041,2367.976822,887.991308,...,791895.271016,296960.726631,0.0,0.0,0.0,0.0,134238.504762,50339.439286,1.749552e+06,656082.065166
33,5.715628e+06,2.143361e+06,0.0,0.0,211588.495763,79345.685911,129.265101,48.474413,2462.619596,923.482349,...,767252.343702,287719.628888,0.0,0.0,0.0,0.0,133015.459640,49880.797365,1.689624e+06,633609.070712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29053,3.528006e+06,1.323002e+06,0.0,0.0,0.000000,0.000000,258.482572,96.930965,3262.826503,1223.559939,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,4.512397e+05,169214.891770
29054,3.418338e+06,1.281877e+06,0.0,0.0,0.000000,0.000000,258.578499,96.966937,3262.495559,1223.435835,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,4.134852e+05,155056.938066
29055,3.306611e+06,1.239979e+06,0.0,0.0,0.000000,0.000000,258.462722,96.923521,3260.025787,1222.509670,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,3.776502e+05,141618.821748
29056,3.192989e+06,1.197371e+06,0.0,0.0,0.000000,0.000000,258.112241,96.792091,3255.249461,1220.718548,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,3.436808e+05,128880.290716
29057,3.077650e+06,1.154119e+06,0.0,0.0,0.000000,0.000000,257.497731,96.561649,3247.923250,1217.971219,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,3.115254e+05,116822.030961

In [156]:
ind_fuel_demand_by_sector[industry_product_vars]

,energy_demand_enfu_subsector_total_pj_entc_fuel_biomass,energy_demand_agriculture_and_livestock_biomass,energy_demand_cement_biomass,energy_demand_chemicals_biomass,energy_demand_electronics_biomass,energy_demand_glass_biomass,energy_demand_lime_and_carbonite_biomass,energy_demand_mining_biomass,energy_demand_other_product_manufacturing_biomass,energy_demand_paper_biomass,...,energy_demand_electronics_oil,energy_demand_glass_oil,energy_demand_lime_and_carbonite_oil,energy_demand_mining_oil,energy_demand_other_product_manufacturing_oil,energy_demand_plastic_oil,energy_demand_recycled_metals_oil,energy_demand_recycled_plastic_oil,energy_demand_rubber_and_leather_oil,energy_demand_wood_oil
29,36.017886,5.148130,0.0,0.285941,0.000083,0.002260,0.0,0.005679,0.031915,67.212892,...,0.005373,0.004605,0.0,0.118219,0.046597,0.701187,0.0,0.0,0.112331,1.736232
30,34.962556,4.831583,0.0,0.268038,0.000095,0.002182,0.0,0.005936,0.033135,65.984351,...,0.005702,0.004902,0.0,0.108145,0.049253,0.707842,0.0,0.0,0.115497,1.690962
31,34.162696,5.188607,0.0,0.241597,0.000103,0.002124,0.0,0.006195,0.034061,64.830062,...,0.005849,0.004732,0.0,0.097837,0.052034,0.717016,0.0,0.0,0.119133,1.632539
32,29.882798,5.164214,0.0,0.214408,0.000110,0.002129,0.0,0.006437,0.034908,63.317225,...,0.006096,0.004524,0.0,0.087263,0.055124,0.712137,0.0,0.0,0.120718,1.573339
33,30.039144,5.139957,0.0,0.190278,0.000116,0.002215,0.0,0.006659,0.035757,61.510920,...,0.006404,0.004484,0.0,0.076504,0.058387,0.689976,0.0,0.0,0.119618,1.519447
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29053,41.647113,3.172670,0.0,0.000000,0.000232,0.002934,0.0,0.005551,0.000357,6.619875,...,0.010790,0.004668,0.0,0.000000,0.000962,0.000000,0.0,0.0,0.000000,0.405791
29054,42.076540,3.074047,0.0,0.000000,0.000233,0.002934,0.0,0.005448,0.000356,4.361418,...,0.010726,0.004633,0.0,0.000000,0.000976,0.000000,0.0,0.0,0.000000,0.371839
29055,42.520829,2.973573,0.0,0.000000,0.000232,0.002932,0.0,0.005344,0.000354,2.148753,...,0.010656,0.004597,0.0,0.000000,0.000988,0.000000,0.0,0.0,0.000000,0.339614
29056,42.980062,2.871395,0.0,0.000000,0.000232,0.002927,0.0,0.005238,0.000352,0.000000,...,0.010579,0.004559,0.0,0.000000,0.001000,0.000000,0.0,0.0,0.000000,0.309066
29057,43.444108,2.767673,0.0,0.000000,0.000232,0.002921,0.0,0.005130,0.000350,0.000000,...,0.010494,0.004519,0.0,0.000000,0.001009,0.000000,0.0,0.0,0.000000,0.280149

In [157]:
# Sum all the subsector emission columns across axis=1
la_production_cost_total_df = ind_fuel_demand_by_sector.copy()
la_production_cost_total_df["production_cost_total"] = la_production_cost_total_df[industry_cost_vars].sum(axis=1)

# Show only the inputs that went into the sum + the result
la_production_cost_total_df[industry_cost_vars + ["production_cost_total"]].head()

,energy_demand_capex_agriculture_and_livestock_biomass,energy_demand_opex_agriculture_and_livestock_biomass,energy_demand_capex_cement_biomass,energy_demand_opex_cement_biomass,energy_demand_capex_chemicals_biomass,energy_demand_opex_chemicals_biomass,energy_demand_capex_electronics_biomass,energy_demand_opex_electronics_biomass,energy_demand_capex_glass_biomass,energy_demand_opex_glass_biomass,...,energy_demand_opex_plastic_oil,energy_demand_capex_recycled_metals_oil,energy_demand_opex_recycled_metals_oil,energy_demand_capex_recycled_plastic_oil,energy_demand_opex_recycled_plastic_oil,energy_demand_capex_rubber_and_leather_oil,energy_demand_opex_rubber_and_leather_oil,energy_demand_capex_wood_oil,energy_demand_opex_wood_oil,production_cost_total
29,5.724716e+06,2.146769e+06,0.0,0.0,317965.809889,119237.178709,92.322045,34.620767,2513.271361,942.476760,...,292394.749847,0.0,0.0,0.0,0.0,124912.074038,46842.027764,1.930689e+06,724008.208766,7.563706e+08
30,5.372716e+06,2.014769e+06,0.0,0.0,298057.573990,111771.590246,105.837249,39.688968,2426.435685,909.913382,...,295170.083911,0.0,0.0,0.0,0.0,128433.029088,48162.385908,1.880348e+06,705130.527630,7.482375e+08
31,5.769727e+06,2.163648e+06,0.0,0.0,268656.188746,100746.070780,114.317824,42.869184,2362.109450,885.791044,...,298995.533754,0.0,0.0,0.0,0.0,132475.520039,49678.320015,1.815382e+06,680768.281295,7.553865e+08
32,5.742602e+06,2.153476e+06,0.0,0.0,238421.547821,89408.080433,122.032109,45.762041,2367.976822,887.991308,...,296960.726631,0.0,0.0,0.0,0.0,134238.504762,50339.439286,1.749552e+06,656082.065166,7.541000e+08
33,5.715628e+06,2.143361e+06,0.0,0.0,211588.495763,79345.685911,129.265101,48.474413,2462.619596,923.482349,...,287719.628888,0.0,0.0,0.0,0.0,133015.459640,49880.797365,1.689624e+06,633609.070712,7.532905e+08

In [158]:
# Keep only the primary_id, time_period, and emission_total columns
la_production_cost_total_df = la_production_cost_total_df[["primary_id", "time_period", "production_cost_total"]]
la_production_cost_total_df.head()

    primary_id  time_period  production_cost_total
29      438438            7           7.563706e+08
30      438438            8           7.482375e+08
31      438438            9           7.553865e+08
32      438438           10           7.541000e+08
33      438438           11           7.532905e+08

In [159]:
# aggregate data by primary_id summing the emissions
la_production_cost_df_mean_agg = la_production_cost_total_df.groupby(["primary_id"]).mean().reset_index()

# Drop time period column
la_production_cost_df_mean_agg = la_production_cost_df_mean_agg.drop(columns=["time_period"])
la_production_cost_df_mean_agg.head()

   primary_id  production_cost_total
0      438438           1.056679e+09
1      438439           1.095336e+09
2      438440           1.134537e+09
3      438441           1.098871e+09
4      438442           1.040931e+09

In [160]:
la_production_cost_df_mean_agg.shape

(1001, 2)

#### production

In [161]:
# columns: base energy demand only (no capex/opex)
industry_product_vars = [
    c for c in ind_fuel_demand_by_sector.columns
    if c.startswith("energy_demand_") and "_capex_" not in c and "_opex_" not in c
]

la_production_total_df = ind_fuel_demand_by_sector.copy()
la_production_total_df["production_total"] = (
    la_production_total_df[industry_product_vars].sum(axis=1, min_count=1)
)

# show only what went into the sum + the result
la_production_total_df[industry_product_vars + ["production_total"]].head()

,energy_demand_enfu_subsector_total_pj_entc_fuel_biomass,energy_demand_agriculture_and_livestock_biomass,energy_demand_cement_biomass,energy_demand_chemicals_biomass,energy_demand_electronics_biomass,energy_demand_glass_biomass,energy_demand_lime_and_carbonite_biomass,energy_demand_mining_biomass,energy_demand_other_product_manufacturing_biomass,energy_demand_paper_biomass,...,energy_demand_glass_oil,energy_demand_lime_and_carbonite_oil,energy_demand_mining_oil,energy_demand_other_product_manufacturing_oil,energy_demand_plastic_oil,energy_demand_recycled_metals_oil,energy_demand_recycled_plastic_oil,energy_demand_rubber_and_leather_oil,energy_demand_wood_oil,production_total
29,36.017886,5.148130,0.0,0.285941,0.000083,0.002260,0.0,0.005679,0.031915,67.212892,...,0.004605,0.0,0.118219,0.046597,0.701187,0.0,0.0,0.112331,1.736232,5924.758692
30,34.962556,4.831583,0.0,0.268038,0.000095,0.002182,0.0,0.005936,0.033135,65.984351,...,0.004902,0.0,0.108145,0.049253,0.707842,0.0,0.0,0.115497,1.690962,5911.202400
31,34.162696,5.188607,0.0,0.241597,0.000103,0.002124,0.0,0.006195,0.034061,64.830062,...,0.004732,0.0,0.097837,0.052034,0.717016,0.0,0.0,0.119133,1.632539,5914.897061
32,29.882798,5.164214,0.0,0.214408,0.000110,0.002129,0.0,0.006437,0.034908,63.317225,...,0.004524,0.0,0.087263,0.055124,0.712137,0.0,0.0,0.120718,1.573339,5918.101023
33,30.039144,5.139957,0.0,0.190278,0.000116,0.002215,0.0,0.006659,0.035757,61.510920,...,0.004484,0.0,0.076504,0.058387,0.689976,0.0,0.0,0.119618,1.519447,5920.629732

In [162]:
# Keep only the primary_id, time_period, and emission_total columns
la_production_total_df = la_production_total_df[["primary_id", "time_period", "production_total"]]
la_production_total_df.head()

    primary_id  time_period  production_total
29      438438            7       5924.758692
30      438438            8       5911.202400
31      438438            9       5914.897061
32      438438           10       5918.101023
33      438438           11       5920.629732

In [163]:
# aggregate data by primary_id summing the emissions
la_production_df_mean_agg = la_production_total_df.groupby(["primary_id"]).mean().reset_index()

# Drop time period column
la_production_df_mean_agg = la_production_df_mean_agg.drop(columns=["time_period"])
la_production_df_mean_agg.head()

   primary_id  production_total
0      438438       8849.651067
1      438439       9825.287358
2      438440       9909.459984
3      438441       9048.903074
4      438442       9410.010340

In [164]:
ind_fuel_demand_by_sector_10_14 = ind_fuel_demand_by_sector
la_production_cost_total_df_10_14 = la_production_cost_total_df
la_production_cost_df_mean_agg_10_14 = la_production_cost_df_mean_agg
la_production_df_mean_agg_10_14 = la_production_df_mean_agg
la_production_total_df_10_14 = la_production_total_df

In [167]:
print('9-18k dimensions: ', ind_fuel_demand_by_sector_9_18.shape)
print('10-14k dimensions: ', ind_fuel_demand_by_sector_10_14.shape)

9-18k dimensions:  (27956, 531)
10-14k dimensions:  (29029, 723)

In [168]:
industry_product_vars_9_18 =  [
    c for c in ind_fuel_demand_by_sector_9_18.columns
    if c.startswith("energy_demand_")
    and "_capex_" not in c
    and "_opex_" not in c
]

industry_product_vars_10_14 =  [
    c for c in ind_fuel_demand_by_sector_10_14.columns
    if c.startswith("energy_demand_")
    and "_capex_" not in c
    and "_opex_" not in c
]


missing_from_9_18 = [value for value in industry_product_vars_10_14 if value not in industry_product_vars_9_18]
missing_from_10_14 = [value for value in industry_product_vars_9_18 if value not in industry_product_vars_10_14]

In [169]:
missing_from_9_18

['energy_demand_agriculture_and_livestock_biomass',
 'energy_demand_glass_biomass',
 'energy_demand_recycled_metals_biomass',
 'energy_demand_wood_biomass',
 'energy_demand_glass_coal',
 'energy_demand_recycled_metals_coal',
 'energy_demand_wood_coal',
 'energy_demand_glass_coke',
 'energy_demand_recycled_metals_coke',
 'energy_demand_wood_coke',
 'energy_demand_agriculture_and_livestock_diesel',
 'energy_demand_glass_diesel',
 'energy_demand_plastic_diesel',
 'energy_demand_recycled_metals_diesel',
 'energy_demand_recycled_plastic_diesel',
 'energy_demand_rubber_and_leather_diesel',
 'energy_demand_wood_diesel',
 'energy_demand_wood_electricity',
 'energy_demand_glass_furnace_gas',
 'energy_demand_recycled_metals_furnace_gas',
 'energy_demand_recycled_textiles_furnace_gas',
 'energy_demand_wood_furnace_gas',
 'energy_demand_agriculture_and_livestock_gasoline',
 'energy_demand_glass_gasoline',
 'energy_demand_plastic_gasoline',
 'energy_demand_recycled_metals_gasoline',
 'energy_demand_recycled_plastic_gasoline',
 'energy_demand_rubber_and_leather_gasoline',
 'energy_demand_wood_gasoline',
 'energy_demand_glass_hydrogen',
 'energy_demand_agriculture_and_livestock_natural_gas',
 'energy_demand_glass_natural_gas',
 'energy_demand_plastic_natural_gas',
 'energy_demand_recycled_metals_natural_gas',
 'energy_demand_recycled_plastic_natural_gas',
 'energy_demand_recycled_textiles_natural_gas',
 'energy_demand_wood_natural_gas',
 'energy_demand_agriculture_and_livestock_oil',
 'energy_demand_glass_oil',
 'energy_demand_plastic_oil',
 'energy_demand_recycled_metals_oil',
 'energy_demand_recycled_plastic_oil',
 'energy_demand_rubber_and_leather_oil',
 'energy_demand_wood_oil']

In [170]:
missing_from_10_14

['energy_demand_recycled_wood_biomass',
 'energy_demand_recycled_wood_coal',
 'energy_demand_other_product_manufacturing_coke',
 'energy_demand_recycled_wood_coke',
 'energy_demand_recycled_wood_diesel',
 'energy_demand_recycled_wood_furnace_gas',
 'energy_demand_textiles_furnace_gas',
 'energy_demand_recycled_wood_gasoline',
 'energy_demand_other_product_manufacturing_hydrogen',
 'energy_demand_recycled_wood_natural_gas',
 'energy_demand_textiles_natural_gas',
 'energy_demand_recycled_wood_oil']

In [171]:
columns_in_both = [value for value in industry_product_vars_10_14 if value in industry_product_vars_9_18]

In [181]:
for col in columns_in_both:
    if ind_fuel_demand_by_sector_9_18[col].mean()>ind_fuel_demand_by_sector_10_14[col].mean():
        print(col)
        print('9-18 average: ',  ind_fuel_demand_by_sector_9_18[col].mean())
        print('10-14 average: ',  ind_fuel_demand_by_sector_10_14[col].mean())

energy_demand_enfu_subsector_total_pj_entc_fuel_biomass
9-18 average:  101.86948195214717
10-14 average:  57.64382699944649
energy_demand_other_product_manufacturing_biomass
9-18 average:  13.69447137181455
10-14 average:  0.5386270240122284
energy_demand_other_product_manufacturing_coal
9-18 average:  0.8709348942347773
10-14 average:  0.06983311461636621
energy_demand_enfu_subsector_total_pj_entc_fuel_coke
9-18 average:  9915.21193940353
10-14 average:  0.0
energy_demand_other_product_manufacturing_diesel
9-18 average:  6.061300433286684
10-14 average:  0.188891805029895
energy_demand_recycled_wood_electricity
9-18 average:  2.9972646107105567
10-14 average:  0.0
energy_demand_textiles_electricity
9-18 average:  0.06791772485186429
10-14 average:  0.0
energy_demand_enfu_subsector_total_pj_entc_fuel_furnace_gas
9-18 average:  24.093530823261297
10-14 average:  0.0
energy_demand_other_product_manufacturing_furnace_gas
9-18 average:  0.8835630500876003
10-14 average:  0.04124752813544444
energy_demand_other_product_manufacturing_gasoline
9-18 average:  6.061300433286684
10-14 average:  0.19707785948211698
energy_demand_enfu_subsector_total_pj_entc_fuel_hydrocarbon_gas_liquids
9-18 average:  51.44365751816088
10-14 average:  0.0008084732923678129
energy_demand_enfu_subsector_total_pj_entc_fuel_kerosene
9-18 average:  7780.520649794286
10-14 average:  1.8436741434784834e-07
energy_demand_other_product_manufacturing_natural_gas
9-18 average:  27.087864662818305
10-14 average:  1.2012458097651086
energy_demand_enfu_subsector_total_pj_entc_fuel_natural_gas_liquid
9-18 average:  27626.20524807486
10-14 average:  1.5846499684095645e-05
energy_demand_other_product_manufacturing_oil
9-18 average:  28.286068688671214
10-14 average:  0.881495090139512

In [177]:
la_production_total_df = ind_fuel_demand_by_sector_10_14.copy()
la_production_total_df["production_total"] = (
    la_production_total_df[columns_in_both].sum(axis=1, min_count=1)
)

# show only what went into the sum + the result
la_production_total_df[columns_in_both + ["production_total"]].head()

,energy_demand_enfu_subsector_total_pj_entc_fuel_biomass,energy_demand_cement_biomass,energy_demand_chemicals_biomass,energy_demand_electronics_biomass,energy_demand_lime_and_carbonite_biomass,energy_demand_mining_biomass,energy_demand_other_product_manufacturing_biomass,energy_demand_paper_biomass,energy_demand_enfu_subsector_total_pj_entc_fuel_coal,energy_demand_cement_coal,...,energy_demand_rubber_and_leather_natural_gas,energy_demand_enfu_subsector_total_pj_entc_fuel_natural_gas_liquid,energy_demand_enfu_subsector_total_pj_entc_fuel_oil,energy_demand_cement_oil,energy_demand_chemicals_oil,energy_demand_electronics_oil,energy_demand_lime_and_carbonite_oil,energy_demand_mining_oil,energy_demand_other_product_manufacturing_oil,production_total
29,36.017886,0.0,0.285941,0.000083,0.0,0.005679,0.031915,67.212892,63.003960,0.0,...,4.159585,0.0,16.318166,0.0,8.507847,0.005373,0.0,0.118219,0.046597,5804.314092
30,34.962556,0.0,0.268038,0.000095,0.0,0.005936,0.033135,65.984351,37.816143,0.0,...,4.288691,0.0,15.863293,0.0,8.483177,0.005702,0.0,0.108145,0.049253,5793.067452
31,34.162696,0.0,0.241597,0.000103,0.0,0.006195,0.034061,64.830062,68.398743,0.0,...,4.441504,0.0,11.587141,0.0,8.497075,0.005849,0.0,0.097837,0.052034,5792.881430
32,29.882798,0.0,0.214408,0.000110,0.0,0.006437,0.034908,63.317225,51.019904,0.0,...,4.594269,0.0,12.276208,0.0,8.505441,0.006096,0.0,0.087263,0.055124,5795.642604
33,30.039144,0.0,0.190278,0.000116,0.0,0.006659,0.035757,61.510920,51.099173,0.0,...,4.764268,0.0,12.340437,0.0,8.522053,0.006404,0.0,0.076504,0.058387,5797.705783

In [178]:
# Keep only the primary_id, time_period, and emission_total columns
la_production_total_df = la_production_total_df[["primary_id", "time_period", "production_total"]]
la_production_total_df.head()

    primary_id  time_period  production_total
29      438438            7       5804.314092
30      438438            8       5793.067452
31      438438            9       5792.881430
32      438438           10       5795.642604
33      438438           11       5797.705783

In [179]:
# aggregate data by primary_id summing the emissions
la_production_df_mean_agg = la_production_total_df.groupby(["primary_id"]).mean().reset_index()

# Drop time period column
la_production_df_mean_agg = la_production_df_mean_agg.drop(columns=["time_period"])
la_production_df_mean_agg.head()

   primary_id  production_total
0      438438       8757.593398
1      438439       9721.301988
2      438440       9797.719612
3      438441       8927.116269
4      438442       9302.377683

In [185]:
energy_demand_cols =  [c for c in wide_inputs_outputs_df.columns
    if c.startswith("energy_demand_enfu_subsector_total_pj_entc_fuel_")
]
energy_demand_cols"

['energy_demand_enfu_subsector_total_pj_entc_fuel_ammonia',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_biofuels',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_biogas',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_biomass',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_coal',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_coke',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_crude',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_diesel',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_electricity',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_furnace_gas',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_gasoline',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_geothermal',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_hydrocarbon_gas_liquids',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_hydrogen',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_kerosene',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_natural_gas',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_natural_gas_liquid',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_nuclear',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_ocean',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_oil',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_other',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_solar',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_waste',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_water',
 'energy_demand_enfu_subsector_total_pj_entc_fuel_wind']