In [ ]:
import pandas as pd
import os
import numpy as np
import joblib

In [10]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [11]:
SCRIPT_DIR_PATH = os.getcwd()
ROOT_DIR_PATH = os.path.dirname(SCRIPT_DIR_PATH)
DATA_DIR_PATH = os.path.join(ROOT_DIR_PATH, "data")
TRAINING_DIR_PATH = os.path.join(DATA_DIR_PATH, "training")
TRAINING_MODELS_DIR_PATH = os.path.join(SCRIPT_DIR_PATH, "trained_models")

In [ ]:
# Load training data to test the model
TRAINING_DATA_PATH = os.path.join(TRAINING_DIR_PATH, "training_data_v4.1.csv")
training_df = pd.read_csv(TRAINING_DATA_PATH)
training_df = training_df.drop(columns=["primary_id", "future_id"])
training_df.head()

,group_1_ef_lvst_entferm,group_2_yf_agrc,group_3_demscalar_soil,group_4_demscalar_ippu,group_5_efficfactor_enfu_industrial_energy_fuel,group_6_elecfuelefficiency_trns,group_7_factor_waso_waste_per_capita_scalar_food,group_8_frac_fgtv,group_9_frac_agrc_agriculture_production_lost,group_10_frac_agrc,...,group_41_pij_lndu_other_to,group_42_pij_lndu_settlements_to,group_43_pij_lndu_wetlands_to,group_44_ef_agrc_anaerobicdom_rice_kg_ch4_ha,group_45_scalar_lvst_carrying_capacity,group_46_scalar_scoe_appliance_energy_demand,group_47_scalar_scoe_heat_energy_demand,emission_avg_last_five_years,emission_total,technical_cost
0,0.952436,0.360397,0.202990,0.995748,0.369859,0.919920,0.478450,0.445798,0.490988,0.510280,...,0.996557,0.053597,0.175103,0.379422,0.438093,0.149362,0.869757,52.248688,3318.009812,-5.143090
1,0.304955,0.204875,0.540658,0.800192,0.206396,0.777352,0.805727,0.536048,0.779857,0.623335,...,0.385371,0.246165,0.101025,0.717013,0.368791,0.774941,0.483352,49.914523,3219.904574,-6.899667
2,0.609262,0.366443,0.601808,0.916668,0.386475,0.181162,0.138910,0.768925,0.884425,0.232722,...,0.601590,0.122444,0.653845,0.216259,0.714853,0.881270,0.581230,-5.154870,2328.191406,-7.129115
3,0.815313,0.487444,0.323954,0.634299,0.064625,0.926815,0.633805,0.439346,0.027114,0.532020,...,0.938985,0.592915,0.564895,0.027725,0.138890,0.820709,0.250616,45.879563,3225.387997,-5.769771
4,0.973878,0.842718,0.884382,0.483039,0.455502,0.003343,0.571994,0.108021,0.346714,0.892123,...,0.492564,0.432240,0.662820,0.179231,0.631375,0.395960,0.661637,24.993688,2740.854420,-8.530492

In [ ]:
# Get a single row from training_df_cleaned for prediction
single_row = training_df.iloc[0].drop(["emission_total", "emission_avg_last_five_years", "technical_cost"])
single_row = single_row.to_frame().T  # Convert to DataFrame
single_row

,group_1_ef_lvst_entferm,group_2_yf_agrc,group_3_demscalar_soil,group_4_demscalar_ippu,group_5_efficfactor_enfu_industrial_energy_fuel,group_6_elecfuelefficiency_trns,group_7_factor_waso_waste_per_capita_scalar_food,group_8_frac_fgtv,group_9_frac_agrc_agriculture_production_lost,group_10_frac_agrc,...,group_38_pij_lndu_forests_primary_to,group_39_pij_lndu_forests_secondary_to,group_40_pij_lndu_grasslands+,group_41_pij_lndu_other_to,group_42_pij_lndu_settlements_to,group_43_pij_lndu_wetlands_to,group_44_ef_agrc_anaerobicdom_rice_kg_ch4_ha,group_45_scalar_lvst_carrying_capacity,group_46_scalar_scoe_appliance_energy_demand,group_47_scalar_scoe_heat_energy_demand
0,0.952436,0.360397,0.20299,0.995748,0.369859,0.91992,0.47845,0.445798,0.490988,0.51028,...,0.941385,0.873715,0.289038,0.996557,0.053597,0.175103,0.379422,0.438093,0.149362,0.869757

In [ ]:
# Predict using the trained model
predictions = xgb_pipeline.predict(single_row)

# Display the predictions
labels = ['emission_total', 'emission_avg_last_five_years', 'technical_cost']
print("Predictions for single row:")
for i, label in enumerate(labels):
    print(f"{label}: {predictions[0][i]:.4f}")

Predictions for single row:
emission_total: 3325.7354
emission_avg_last_five_years: 52.6001
technical_cost: -5.1087