In [1]:
import pandas as pd
import os

In [2]:
# Set up paths
SCRIPT_DIR_PATH = os.getcwd()
CW_DIR_PATH = os.path.join(SCRIPT_DIR_PATH, "cw")
DATA_DIR_PATH = os.path.join(SCRIPT_DIR_PATH, "data")
OUTPUT_DIR_PATH = os.path.join(SCRIPT_DIR_PATH, "output")

In [3]:
cb_df = pd.read_csv(os.path.join(OUTPUT_DIR_PATH, "combined_cb_results_de38bb46-7d00-4cf5-8844-f6cc20695024.csv"))
cb_df.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,primary_id
0,PFLO:ALL_LA_ACTIONS,878,louisiana,7.0,pop_unimproved_rural,299091.209054,299711.507625,620.298571,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,355232
1,PFLO:ALL_LA_ACTIONS,878,louisiana,8.0,pop_unimproved_rural,294340.078493,295270.526350,930.447856,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,355232
2,PFLO:ALL_LA_ACTIONS,878,louisiana,9.0,pop_unimproved_rural,289474.711388,290715.308530,1240.597142,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,355232
3,PFLO:ALL_LA_ACTIONS,878,louisiana,10.0,pop_unimproved_rural,284494.629299,286045.375726,1550.746427,cb:wali:technical_cost:sanitation:unimp_rural,-10079.851778,355232
4,PFLO:ALL_LA_ACTIONS,878,louisiana,11.0,pop_unimproved_rural,279403.968085,281264.863798,1860.895713,cb:wali:technical_cost:sanitation:unimp_rural,-12095.822134,355232

In [4]:
# evaluate each column null values
null_counts = cb_df.isnull().sum()
print("Null values in each column:")
print(null_counts)

Null values in each column:
strategy_code                  0
future_id                      0
region                         0
time_period                    0
difference_variable            0
variable_value_baseline    84560
variable_value_pathway         0
difference_value           84560
variable                       0
value                      78596
primary_id                     0
dtype: int64

In [12]:
null_baseline = cb_df[cb_df['variable_value_baseline'].isnull()]
null_baseline

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,primary_id
5760,PFLO:ALL_LA_ACTIONS,878,louisiana,25.0,energy_demand_enfu_total_fuel_coal,NaN,0.852621,NaN,cb:fgtv:technical_cost:flaring:X,NaN,355232
5761,PFLO:ALL_LA_ACTIONS,878,louisiana,26.0,energy_demand_enfu_total_fuel_coal,NaN,0.840204,NaN,cb:fgtv:technical_cost:flaring:X,NaN,355232
5762,PFLO:ALL_LA_ACTIONS,878,louisiana,27.0,energy_demand_enfu_total_fuel_coal,NaN,0.827280,NaN,cb:fgtv:technical_cost:flaring:X,NaN,355232
5763,PFLO:ALL_LA_ACTIONS,878,louisiana,28.0,energy_demand_enfu_total_fuel_coal,NaN,0.813852,NaN,cb:fgtv:technical_cost:flaring:X,NaN,355232
5764,PFLO:ALL_LA_ACTIONS,878,louisiana,29.0,energy_demand_enfu_total_fuel_coal,NaN,0.799933,NaN,cb:fgtv:technical_cost:flaring:X,NaN,355232
...,...,...,...,...,...,...,...,...,...,...,...
7379361,PFLO:ALL_LA_ACTIONS,861,louisiana,18.0,energy_demand_enfu_total_fuel_oil,NaN,0.985952,NaN,cb:fgtv:technical_cost:flaring:X_shifted2023.0,NaN,355215
7379362,PFLO:ALL_LA_ACTIONS,861,louisiana,19.0,energy_demand_enfu_total_fuel_oil,NaN,0.394269,NaN,cb:fgtv:technical_cost:flaring:X_shifted2024.0,NaN,355215
7379369,PFLO:ALL_LA_ACTIONS,861,louisiana,17.0,energy_demand_enfu_total_fuel_oil,NaN,0.390624,NaN,cb:fgtv:technical_cost:leaks:X_shifted2022.0,NaN,355215
7379370,PFLO:ALL_LA_ACTIONS,861,louisiana,18.0,energy_demand_enfu_total_fuel_oil,NaN,0.985952,NaN,cb:fgtv:technical_cost:leaks:X_shifted2023.0,NaN,355215
7379371,PFLO:ALL_LA_ACTIONS,861,louisiana,19.0,energy_demand_enfu_total_fuel_oil,NaN,0.394269,NaN,cb:fgtv:technical_cost:leaks:X_shifted2024.0,NaN,355215

In [13]:
null_baseline.variable.unique()  # Check unique future_ids with null baseline values

array(['cb:fgtv:technical_cost:flaring:X',
       'cb:fgtv:technical_cost:leaks:X',
       'cb:fgtv:technical_cost:flaring:X_shifted2022.0',
       'cb:fgtv:technical_cost:flaring:X_shifted2023.0',
       'cb:fgtv:technical_cost:flaring:X_shifted2024.0',
       'cb:fgtv:technical_cost:leaks:X_shifted2022.0',
       'cb:fgtv:technical_cost:leaks:X_shifted2023.0',
       'cb:fgtv:technical_cost:leaks:X_shifted2024.0'], dtype=object)

In [14]:
# replace all nans with 0
cb_df.fillna(0, inplace=True)
# Check if there are still any null values
null_counts_after_fill = cb_df.isnull().sum()
print("Null values after fillna:")
print(null_counts_after_fill)

Null values after fillna:
strategy_code              0
future_id                  0
region                     0
time_period                0
difference_variable        0
variable_value_baseline    0
variable_value_pathway     0
difference_value           0
variable                   0
value                      0
primary_id                 0
dtype: int64

In [15]:
# Save updated DataFrame
cb_df.to_csv(os.path.join(OUTPUT_DIR_PATH, "combined_cb_results_updated.csv"), index=False)
print("Updated DataFrame saved to combined_cb_results_updated.csv")

Updated DataFrame saved to combined_cb_results_updated.csv

## Check wide file

In [17]:
wide_cb_df = pd.read_csv(os.path.join(OUTPUT_DIR_PATH, "wide_cb_data_lhcde38bb46-7d00-4cf5-8844-f6cc20695024.csv"))
wide_cb_df.head()

,primary_id,future_id,strategy_code,Year,air_pollution,congestion,consumer_savings,crop_value,ecosystem_services,env_pollution,...,human_health,ippu_value,land_pollution,lvst_value,road_safety,sector_specific,system_cost,technical_cost,technical_savings,water_pollution
0,354355,1,PFLO:ALL_LA_ACTIONS,2022.0,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,354355,1,PFLO:ALL_LA_ACTIONS,2023.0,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,354355,1,PFLO:ALL_LA_ACTIONS,2024.0,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,354355,1,PFLO:ALL_LA_ACTIONS,2025.0,0.060282,0.132495,0.021720,4.143264e-14,-3.977853e-13,0.000014,...,0.018795,-0.053377,-1.193712e-17,-0.131033,0.210159,7536.242379,37.153191,0.619617,0.207821,-0.025037
4,354355,1,PFLO:ALL_LA_ACTIONS,2026.0,0.073026,0.159321,0.043711,-1.172087e-14,4.620699e-13,0.000017,...,0.038597,-0.057632,1.875833e-17,-0.156095,0.252749,9164.677971,45.045727,-0.196941,0.192236,-0.030054

In [18]:
# check for null values in wide file
wide_null_counts = wide_cb_df.isnull().sum()
print("Null values in wide DataFrame:")
print(wide_null_counts)

Null values in wide DataFrame:
primary_id            0
future_id             0
strategy_code         0
Year                  0
air_pollution         0
congestion            0
consumer_savings      0
crop_value            0
ecosystem_services    0
env_pollution         0
fuel_cost             0
human_health          0
ippu_value            0
land_pollution        0
lvst_value            0
road_safety           0
sector_specific       0
system_cost           0
technical_cost        0
technical_savings     0
water_pollution       0
dtype: int64