In [22]:
import pandas as pd
import os

In [23]:
# Set up paths
SCRIPT_DIR_PATH = os.getcwd()
CW_DIR_PATH = os.path.join(SCRIPT_DIR_PATH, "cw")
DATA_DIR_PATH = os.path.join(SCRIPT_DIR_PATH, "data")
ENSEMBLE_DIR_PATH = os.path.join(DATA_DIR_PATH, "ensemble_data")
RUN_DIR_PATH = os.path.join(ENSEMBLE_DIR_PATH, "sisepuede_summary_results_run_sisepuede_run_2025-08-10t10;29;30.545790")

In [24]:
cb_df = pd.read_csv(os.path.join(RUN_DIR_PATH, "combined_cb_results_updated.csv"))
cb_df.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,primary_id
0,PFLO:ALL_LA_ACTIONS,878,louisiana,7.0,pop_unimproved_rural,299091.209054,299711.507625,620.298571,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,355232
1,PFLO:ALL_LA_ACTIONS,878,louisiana,8.0,pop_unimproved_rural,294340.078493,295270.526350,930.447856,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,355232
2,PFLO:ALL_LA_ACTIONS,878,louisiana,9.0,pop_unimproved_rural,289474.711388,290715.308530,1240.597142,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,355232
3,PFLO:ALL_LA_ACTIONS,878,louisiana,10.0,pop_unimproved_rural,284494.629299,286045.375726,1550.746427,cb:wali:technical_cost:sanitation:unimp_rural,-10079.851778,355232
4,PFLO:ALL_LA_ACTIONS,878,louisiana,11.0,pop_unimproved_rural,279403.968085,281264.863798,1860.895713,cb:wali:technical_cost:sanitation:unimp_rural,-12095.822134,355232

In [25]:
# evaluate each column null values
null_counts = cb_df.isnull().sum()
print("Null values in each column:")
print(null_counts)

Null values in each column:
strategy_code              0
future_id                  0
region                     0
time_period                0
difference_variable        0
variable_value_baseline    0
variable_value_pathway     0
difference_value           0
variable                   0
value                      0
primary_id                 0
dtype: int64

In [26]:
null_baseline = cb_df[cb_df['variable_value_baseline'].isnull()]
null_baseline

Empty DataFrame
Columns: [strategy_code, future_id, region, time_period, difference_variable, variable_value_baseline, variable_value_pathway, difference_value, variable, value, primary_id]
Index: []

In [27]:
null_baseline.variable.unique()  # Check unique future_ids with null baseline values

array([], dtype=object)

In [28]:
# Check for -inf values in numeric columns
negative_inf_counts = (cb_df == -float('inf')).sum()
print("Negative infinity counts in each column:")
print(negative_inf_counts)

Negative infinity counts in each column:
strategy_code              0
future_id                  0
region                     0
time_period                0
difference_variable        0
variable_value_baseline    0
variable_value_pathway     0
difference_value           0
variable                   0
value                      0
primary_id                 0
dtype: int64

In [16]:
# check the rows with -inf values in 'value' column
negative_inf_rows = cb_df[cb_df['value'] == -float('inf')]
print("Rows with -inf in 'value' column:")
negative_inf_rows

Rows with -inf in 'value' column:

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,primary_id
1936000,PFLO:ALL_LA_ACTIONS,576,louisiana,25.0,energy_demand_enfu_total_fuel_coal,inf,0.002320,-inf,cb:fgtv:technical_cost:flaring:X,-inf,354930
1936001,PFLO:ALL_LA_ACTIONS,576,louisiana,26.0,energy_demand_enfu_total_fuel_coal,inf,0.002565,-inf,cb:fgtv:technical_cost:flaring:X,-inf,354930
1936002,PFLO:ALL_LA_ACTIONS,576,louisiana,27.0,energy_demand_enfu_total_fuel_coal,inf,0.002817,-inf,cb:fgtv:technical_cost:flaring:X,-inf,354930
1936003,PFLO:ALL_LA_ACTIONS,576,louisiana,28.0,energy_demand_enfu_total_fuel_coal,inf,0.003073,-inf,cb:fgtv:technical_cost:flaring:X,-inf,354930
1936004,PFLO:ALL_LA_ACTIONS,576,louisiana,29.0,energy_demand_enfu_total_fuel_coal,inf,0.003333,-inf,cb:fgtv:technical_cost:flaring:X,-inf,354930
...,...,...,...,...,...,...,...,...,...,...,...
5358557,PFLO:ALL_LA_ACTIONS,584,louisiana,31.0,energy_demand_enfu_total_fuel_coal,inf,0.003998,-inf,cb:fgtv:technical_cost:leaks:X,-inf,354938
5358558,PFLO:ALL_LA_ACTIONS,584,louisiana,32.0,energy_demand_enfu_total_fuel_coal,inf,0.004166,-inf,cb:fgtv:technical_cost:leaks:X,-inf,354938
5358559,PFLO:ALL_LA_ACTIONS,584,louisiana,33.0,energy_demand_enfu_total_fuel_coal,inf,0.004322,-inf,cb:fgtv:technical_cost:leaks:X,-inf,354938
5358560,PFLO:ALL_LA_ACTIONS,584,louisiana,34.0,energy_demand_enfu_total_fuel_coal,inf,0.004465,-inf,cb:fgtv:technical_cost:leaks:X,-inf,354938
5358561,PFLO:ALL_LA_ACTIONS,584,louisiana,35.0,energy_demand_enfu_total_fuel_coal,inf,0.004596,-inf,cb:fgtv:technical_cost:leaks:X,-inf,354938

In [17]:
# replace -inf with 0 in 'value' column
cb_df['value'] = cb_df['value'].replace(-float('inf'), 0)
cb_df['difference_value'] = cb_df['difference_value'].replace(-float('inf'), 0)

In [18]:
# Check for -inf values in numeric columns
negative_inf_counts = (cb_df == -float('inf')).sum()
print("Negative infinity counts in each column:")
print(negative_inf_counts)

Negative infinity counts in each column:
strategy_code              0
future_id                  0
region                     0
time_period                0
difference_variable        0
variable_value_baseline    0
variable_value_pathway     0
difference_value           0
variable                   0
value                      0
primary_id                 0
dtype: int64

In [19]:
# replace all nans with 0
cb_df.fillna(0, inplace=True)
# Check if there are still any null values
null_counts_after_fill = cb_df.isnull().sum()
print("Null values after fillna:")
print(null_counts_after_fill)

Null values after fillna:
strategy_code              0
future_id                  0
region                     0
time_period                0
difference_variable        0
variable_value_baseline    0
variable_value_pathway     0
difference_value           0
variable                   0
value                      0
primary_id                 0
dtype: int64

In [21]:
# Save updated DataFrame
cb_df.to_csv(os.path.join(RUN_DIR_PATH, "combined_cb_results_updated.csv"), index=False)
print("Updated DataFrame saved to combined_cb_results_updated.csv")

Updated DataFrame saved to combined_cb_results_updated.csv

## Check wide file

In [29]:
wide_cb_df = pd.read_csv(os.path.join(RUN_DIR_PATH, "wide_cb_data_lhc_2025-08-10t10;29;30.545790.csv"))
wide_cb_df.head()

,primary_id,future_id,strategy_code,Year,air_pollution,congestion,consumer_savings,crop_value,ecosystem_services,env_pollution,...,human_health,ippu_value,land_pollution,lvst_value,road_safety,sector_specific,system_cost,technical_cost,technical_savings,water_pollution
0,354355,1,PFLO:ALL_LA_ACTIONS,2022.0,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,354355,1,PFLO:ALL_LA_ACTIONS,2023.0,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,354355,1,PFLO:ALL_LA_ACTIONS,2024.0,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,354355,1,PFLO:ALL_LA_ACTIONS,2025.0,0.060282,0.132495,0.021720,4.143264e-14,-3.977853e-13,0.000014,...,0.018795,-0.053377,-1.193712e-17,-0.131033,0.210159,7536.242379,37.153191,0.619617,0.207821,-0.025037
4,354355,1,PFLO:ALL_LA_ACTIONS,2026.0,0.073026,0.159321,0.043711,-1.172087e-14,4.620699e-13,0.000017,...,0.038597,-0.057632,1.875833e-17,-0.156095,0.252749,9164.677971,45.045727,-0.196941,0.192236,-0.030054

In [30]:
# check for null values in wide file
wide_null_counts = wide_cb_df.isnull().sum()
print("Null values in wide DataFrame:")
print(wide_null_counts)

Null values in wide DataFrame:
primary_id            0
future_id             0
strategy_code         0
Year                  0
air_pollution         0
congestion            0
consumer_savings      0
crop_value            0
ecosystem_services    0
env_pollution         0
fuel_cost             0
human_health          0
ippu_value            0
land_pollution        0
lvst_value            0
road_safety           0
sector_specific       0
system_cost           0
technical_cost        0
technical_savings     0
water_pollution       0
dtype: int64

In [31]:
# check for inf and -inf values in wide file
wide_negative_inf_counts = (wide_cb_df == -float('inf')).sum()
print("Negative infinity counts in wide DataFrame:")
print(wide_negative_inf_counts)

Negative infinity counts in wide DataFrame:
primary_id            0
future_id             0
strategy_code         0
Year                  0
air_pollution         0
congestion            0
consumer_savings      0
crop_value            0
ecosystem_services    0
env_pollution         0
fuel_cost             0
human_health          0
ippu_value            0
land_pollution        0
lvst_value            0
road_safety           0
sector_specific       0
system_cost           0
technical_cost        0
technical_savings     0
water_pollution       0
dtype: int64