In [2]:
import os
import pandas as pd
import numpy as np

In [3]:
# Set up paths
SCRIPT_DIR_PATH = os.getcwd()
CW_DIR_PATH = os.path.join(SCRIPT_DIR_PATH, "cw")
DATA_DIR_PATH = os.path.join(SCRIPT_DIR_PATH, "data")
OUTPUT_DIR_PATH = os.path.join(SCRIPT_DIR_PATH, "output")

In [4]:
raw_df = pd.read_csv(os.path.join(DATA_DIR_PATH, "549fa196-773e-47bc-b8b4-a618fe081cb3.csv"))
raw_df.head()

,primary_id,region,time_period,area_agrc_crops_bevs_and_spices,area_agrc_crops_cereals,area_agrc_crops_fibers,area_agrc_crops_fruits,area_agrc_crops_herbs_and_other_perennial_crops,area_agrc_crops_nuts,area_agrc_crops_other_annual,...,emission_co2e_subsector_total_soil,emission_co2e_subsector_total_waso,emission_co2e_subsector_total_trww,emission_co2e_subsector_total_ccsq,emission_co2e_subsector_total_entc,emission_co2e_subsector_total_fgtv,emission_co2e_subsector_total_inen,emission_co2e_subsector_total_scoe,emission_co2e_subsector_total_trns,emission_co2e_subsector_total_ippu
0,354354,louisiana,0,0.0,367983.831774,68239.857458,80.234375,79198.541655,6714.566582,1.154590e+06,...,0.000329,3.641483,0.0,0.189831,0.0,0.0,0.0,0.0,4.217251,174.643802
1,354354,louisiana,1,0.0,366050.112647,67881.263666,79.812752,78782.361047,6679.282190,1.148523e+06,...,0.000314,3.401604,0.0,0.176563,0.0,0.0,0.0,0.0,3.939500,165.142182
2,354354,louisiana,2,0.0,364126.544698,67524.552334,79.393341,78368.365205,6644.183026,1.142487e+06,...,0.000314,3.659043,0.0,0.171586,0.0,0.0,0.0,0.0,4.237636,162.684942
3,354354,louisiana,3,0.0,362832.342107,67284.552115,79.111156,78089.823191,6620.567832,1.138427e+06,...,0.000332,4.071168,0.0,0.175757,0.0,0.0,0.0,0.0,4.714950,171.626173
4,354354,louisiana,4,0.0,361132.180759,66969.269871,78.740457,77723.909562,6589.545147,1.133092e+06,...,0.000309,3.995719,0.0,0.181465,0.0,0.0,0.0,0.0,4.627545,162.470893

In [6]:
raw_df[raw_df.primary_id == 0].head()

Empty DataFrame
Columns: [primary_id, region, time_period, area_agrc_crops_bevs_and_spices, area_agrc_crops_cereals, area_agrc_crops_fibers, area_agrc_crops_fruits, area_agrc_crops_herbs_and_other_perennial_crops, area_agrc_crops_nuts, area_agrc_crops_other_annual, area_agrc_crops_other_woody_perennial, area_agrc_crops_pulses, area_agrc_crops_rice, area_agrc_crops_sugar_cane, area_agrc_crops_tubers, area_agrc_crops_vegetables_and_vines, area_gnrl_country_ha, area_lndu_conversion_from_croplands, area_lndu_conversion_from_croplands_to_croplands, area_lndu_conversion_from_croplands_to_flooded, area_lndu_conversion_from_croplands_to_forests_mangroves, area_lndu_conversion_from_croplands_to_forests_primary, area_lndu_conversion_from_croplands_to_forests_secondary, area_lndu_conversion_from_croplands_to_grasslands, area_lndu_conversion_from_croplands_to_other, area_lndu_conversion_from_croplands_to_pastures, area_lndu_conversion_from_croplands_to_settlements, area_lndu_conversion_from_croplands_to_shrublands, area_lndu_conversion_from_croplands_to_wetlands, area_lndu_conversion_from_flooded, area_lndu_conversion_from_flooded_to_croplands, area_lndu_conversion_from_flooded_to_flooded, area_lndu_conversion_from_flooded_to_forests_mangroves, area_lndu_conversion_from_flooded_to_forests_primary, area_lndu_conversion_from_flooded_to_forests_secondary, area_lndu_conversion_from_flooded_to_grasslands, area_lndu_conversion_from_flooded_to_other, area_lndu_conversion_from_flooded_to_pastures, area_lndu_conversion_from_flooded_to_settlements, area_lndu_conversion_from_flooded_to_shrublands, area_lndu_conversion_from_flooded_to_wetlands, area_lndu_conversion_from_forests_mangroves, area_lndu_conversion_from_forests_mangroves_to_croplands, area_lndu_conversion_from_forests_mangroves_to_flooded, area_lndu_conversion_from_forests_mangroves_to_forests_mangroves, area_lndu_conversion_from_forests_mangroves_to_forests_primary, area_lndu_conversion_from_forests_mangroves_to_forests_secondary, area_lndu_conversion_from_forests_mangroves_to_grasslands, area_lndu_conversion_from_forests_mangroves_to_other, area_lndu_conversion_from_forests_mangroves_to_pastures, area_lndu_conversion_from_forests_mangroves_to_settlements, area_lndu_conversion_from_forests_mangroves_to_shrublands, area_lndu_conversion_from_forests_mangroves_to_wetlands, area_lndu_conversion_from_forests_primary, area_lndu_conversion_from_forests_primary_to_croplands, area_lndu_conversion_from_forests_primary_to_flooded, area_lndu_conversion_from_forests_primary_to_forests_mangroves, area_lndu_conversion_from_forests_primary_to_forests_primary, area_lndu_conversion_from_forests_primary_to_forests_secondary, area_lndu_conversion_from_forests_primary_to_grasslands, area_lndu_conversion_from_forests_primary_to_other, area_lndu_conversion_from_forests_primary_to_pastures, area_lndu_conversion_from_forests_primary_to_settlements, area_lndu_conversion_from_forests_primary_to_shrublands, area_lndu_conversion_from_forests_primary_to_wetlands, area_lndu_conversion_from_forests_secondary, area_lndu_conversion_from_forests_secondary_to_croplands, area_lndu_conversion_from_forests_secondary_to_flooded, area_lndu_conversion_from_forests_secondary_to_forests_mangroves, area_lndu_conversion_from_forests_secondary_to_forests_primary, area_lndu_conversion_from_forests_secondary_to_forests_secondary, area_lndu_conversion_from_forests_secondary_to_grasslands, area_lndu_conversion_from_forests_secondary_to_other, area_lndu_conversion_from_forests_secondary_to_pastures, area_lndu_conversion_from_forests_secondary_to_settlements, area_lndu_conversion_from_forests_secondary_to_shrublands, area_lndu_conversion_from_forests_secondary_to_wetlands, area_lndu_conversion_from_grasslands, area_lndu_conversion_from_grasslands_to_croplands, area_lndu_conversion_from_grasslands_to_flooded, area_lndu_conversion_from_grasslands_to_forests_mangroves, area_lndu_conversion_from_grasslands_to_forests_primary, area_lndu_conversion_from_grasslands_to_forests_secondary, area_lndu_conversion_from_grasslands_to_grasslands, area_lndu_conversion_from_grasslands_to_other, area_lndu_conversion_from_grasslands_to_pastures, area_lndu_conversion_from_grasslands_to_settlements, area_lndu_conversion_from_grasslands_to_shrublands, area_lndu_conversion_from_grasslands_to_wetlands, area_lndu_conversion_from_other, area_lndu_conversion_from_other_to_croplands, area_lndu_conversion_from_other_to_flooded, area_lndu_conversion_from_other_to_forests_mangroves, area_lndu_conversion_from_other_to_forests_primary, area_lndu_conversion_from_other_to_forests_secondary, area_lndu_conversion_from_other_to_grasslands, area_lndu_conversion_from_other_to_other, area_lndu_conversion_from_other_to_pastures, area_lndu_conversion_from_other_to_settlements, area_lndu_conversion_from_other_to_shrublands, ...]
Index: []

[0 rows x 3975 columns]