In [1]:
import pandas as pd
import os

In [2]:
# Set up paths
SCRIPT_DIR_PATH = os.getcwd()
CW_DIR_PATH = os.path.join(SCRIPT_DIR_PATH, "cw")
DATA_DIR_PATH = os.path.join(SCRIPT_DIR_PATH, "data")
ENSEMBLE_DIR_PATH = os.path.join(DATA_DIR_PATH, "ensemble_data")
run_id = "2025-08-28t15;29;22.344855"
RUN_DIR_PATH = os.path.join(ENSEMBLE_DIR_PATH, f"sisepuede_summary_results_run_sisepuede_run_{run_id}")

In [3]:
# cb_df = pd.read_csv(os.path.join(RUN_DIR_PATH, f"cba_la_{run_id}.csv"))
cb_df = pd.read_csv(os.path.join(RUN_DIR_PATH, f"combined_cb_results_{run_id}.csv"))
cb_df.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,primary_id
0,PFLO:ALL_LA_ACTIONS,878,louisiana,7.0,pop_unimproved_rural,299091.209054,299312.657905,221.448851,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,403279
1,PFLO:ALL_LA_ACTIONS,878,louisiana,8.0,pop_unimproved_rural,294340.078493,294672.251770,332.173276,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,403279
2,PFLO:ALL_LA_ACTIONS,878,louisiana,9.0,pop_unimproved_rural,289474.711388,289917.609090,442.897702,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,403279
3,PFLO:ALL_LA_ACTIONS,878,louisiana,10.0,pop_unimproved_rural,284494.629299,285048.251426,553.622127,cb:wali:technical_cost:sanitation:unimp_rural,-3598.543828,403279
4,PFLO:ALL_LA_ACTIONS,878,louisiana,11.0,pop_unimproved_rural,279403.968085,280068.314638,664.346553,cb:wali:technical_cost:sanitation:unimp_rural,-4318.252593,403279

In [4]:
# evaluate each column null values
null_counts = cb_df.isnull().sum()
print("Null values in each column:")
print(null_counts)

Null values in each column:
strategy_code                   0
future_id                       0
region                          0
time_period                     0
difference_variable             0
variable_value_baseline    148650
variable_value_pathway          0
difference_value           148650
variable                        0
value                      136758
primary_id                      0
dtype: int64

In [5]:
null_baseline = cb_df[cb_df['variable_value_baseline'].isnull()]
null_baseline

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,primary_id
5760,PFLO:ALL_LA_ACTIONS,878,louisiana,25.0,energy_demand_enfu_total_fuel_coal,NaN,1.541429,NaN,cb:fgtv:technical_cost:flaring:X,NaN,403279
5761,PFLO:ALL_LA_ACTIONS,878,louisiana,26.0,energy_demand_enfu_total_fuel_coal,NaN,1.405032,NaN,cb:fgtv:technical_cost:flaring:X,NaN,403279
5762,PFLO:ALL_LA_ACTIONS,878,louisiana,27.0,energy_demand_enfu_total_fuel_coal,NaN,1.242704,NaN,cb:fgtv:technical_cost:flaring:X,NaN,403279
5763,PFLO:ALL_LA_ACTIONS,878,louisiana,28.0,energy_demand_enfu_total_fuel_coal,NaN,1.088959,NaN,cb:fgtv:technical_cost:flaring:X,NaN,403279
5764,PFLO:ALL_LA_ACTIONS,878,louisiana,29.0,energy_demand_enfu_total_fuel_coal,NaN,0.943827,NaN,cb:fgtv:technical_cost:flaring:X,NaN,403279
...,...,...,...,...,...,...,...,...,...,...,...
7357095,PFLO:ALL_LA_ACTIONS,861,louisiana,18.0,energy_demand_enfu_total_fuel_natural_gas,NaN,13.316284,NaN,cb:fgtv:technical_cost:leaks:X_shifted2023.0,NaN,403262
7357096,PFLO:ALL_LA_ACTIONS,861,louisiana,19.0,energy_demand_enfu_total_fuel_natural_gas,NaN,12.645022,NaN,cb:fgtv:technical_cost:leaks:X_shifted2024.0,NaN,403262
7357097,PFLO:ALL_LA_ACTIONS,861,louisiana,17.0,energy_demand_enfu_total_fuel_oil,NaN,0.262760,NaN,cb:fgtv:technical_cost:leaks:X_shifted2022.0,NaN,403262
7357098,PFLO:ALL_LA_ACTIONS,861,louisiana,18.0,energy_demand_enfu_total_fuel_oil,NaN,0.587476,NaN,cb:fgtv:technical_cost:leaks:X_shifted2023.0,NaN,403262
7357099,PFLO:ALL_LA_ACTIONS,861,louisiana,19.0,energy_demand_enfu_total_fuel_oil,NaN,0.268270,NaN,cb:fgtv:technical_cost:leaks:X_shifted2024.0,NaN,403262

In [6]:
null_baseline.variable.unique()  # Check unique future_ids with null baseline values

array(['cb:fgtv:technical_cost:flaring:X',
       'cb:fgtv:technical_cost:leaks:X',
       'cb:fgtv:technical_cost:flaring:X_shifted2022.0',
       'cb:fgtv:technical_cost:flaring:X_shifted2023.0',
       'cb:fgtv:technical_cost:flaring:X_shifted2024.0',
       'cb:fgtv:technical_cost:leaks:X_shifted2022.0',
       'cb:fgtv:technical_cost:leaks:X_shifted2023.0',
       'cb:fgtv:technical_cost:leaks:X_shifted2024.0'], dtype=object)

In [7]:
# Check for -inf values in numeric columns
negative_inf_counts = (cb_df == -float('inf')).sum()
print("Negative infinity counts in each column:")
print(negative_inf_counts)

Negative infinity counts in each column:
strategy_code              0
future_id                  0
region                     0
time_period                0
difference_variable        0
variable_value_baseline    0
variable_value_pathway     0
difference_value           0
variable                   0
value                      0
primary_id                 0
dtype: int64

In [8]:
# check the rows with -inf values in 'value' column
negative_inf_rows = cb_df[cb_df['value'] == -float('inf')]
print("Rows with -inf in 'value' column:")
negative_inf_rows

Rows with -inf in 'value' column:

Empty DataFrame
Columns: [strategy_code, future_id, region, time_period, difference_variable, variable_value_baseline, variable_value_pathway, difference_value, variable, value, primary_id]
Index: []

In [9]:
# # replace -inf with 0 in 'value' column
# cb_df['value'] = cb_df['value'].replace(-float('inf'), 0)
# cb_df['difference_value'] = cb_df['difference_value'].replace(-float('inf'), 0)

In [10]:
# Check for -inf values in numeric columns
negative_inf_counts = (cb_df == -float('inf')).sum()
print("Negative infinity counts in each column:")
print(negative_inf_counts)

Negative infinity counts in each column:
strategy_code              0
future_id                  0
region                     0
time_period                0
difference_variable        0
variable_value_baseline    0
variable_value_pathway     0
difference_value           0
variable                   0
value                      0
primary_id                 0
dtype: int64

In [11]:
# replace all nans with 0
cb_df.fillna(0, inplace=True)
# Check if there are still any null values
null_counts_after_fill = cb_df.isnull().sum()
print("Null values after fillna:")
print(null_counts_after_fill)

Null values after fillna:
strategy_code              0
future_id                  0
region                     0
time_period                0
difference_variable        0
variable_value_baseline    0
variable_value_pathway     0
difference_value           0
variable                   0
value                      0
primary_id                 0
dtype: int64

In [12]:
# # Save updated DataFrame
# cb_df.to_csv(os.path.join(RUN_DIR_PATH, f"combined_cb_results_updated_{run_id}.csv"), index=False)
# print(f"Updated DataFrame saved to combined_cb_results_updated_{run_id}.csv")

## Check wide file

In [13]:
wide_cb_df = pd.read_csv(os.path.join(RUN_DIR_PATH, "wide_cb_data_lhc_2025-08-28t15;29;22.344855.csv"))
wide_cb_df.head()

,primary_id,future_id,strategy_code,Year,air_pollution,congestion,consumer_savings,crop_value,ecosystem_services,env_pollution,...,human_health,ippu_value,land_pollution,lvst_value,road_safety,sector_specific,system_cost,technical_cost,technical_savings,water_pollution
0,402402,1,PFLO:ALL_LA_ACTIONS,2022.0,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.0,...,0.000000,0.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0
1,402402,1,PFLO:ALL_LA_ACTIONS,2023.0,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.0,...,0.000000,0.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0
2,402402,1,PFLO:ALL_LA_ACTIONS,2024.0,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.0,...,0.000000,0.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0
3,402402,1,PFLO:ALL_LA_ACTIONS,2025.0,9.695006e-16,-1.451481e-23,0.021749,0.000000e+00,6.959355e-12,0.0,...,0.019772,0.0,0.000000e+00,0.0,-2.494771e-23,5.093170e-14,0.000000e+00,-0.021329,0.000000e+00,0.0
4,402402,1,PFLO:ALL_LA_ACTIONS,2026.0,1.425974e-16,0.000000e+00,0.043782,2.673078e-14,7.691665e-12,0.0,...,0.039802,0.0,-5.968559e-17,0.0,0.000000e+00,-5.563550e-14,-5.269051e-15,-0.072557,8.114148e-17,0.0

In [14]:
# check for null values in wide file
wide_null_counts = wide_cb_df.isnull().sum()
print("Null values in wide DataFrame:")
print(wide_null_counts)

Null values in wide DataFrame:
primary_id             0
future_id              0
strategy_code          0
Year                   0
air_pollution          0
congestion            29
consumer_savings      29
crop_value             0
ecosystem_services     0
env_pollution         29
fuel_cost             29
human_health           0
ippu_value            29
land_pollution        29
lvst_value             0
road_safety           29
sector_specific       29
system_cost            0
technical_cost         0
technical_savings     29
water_pollution       29
dtype: int64

In [17]:
wide_cb_df.fillna(0, inplace=True)
wide_cb_df.to_csv(os.path.join(RUN_DIR_PATH, f"wide_cb_data_lhc_{run_id}.csv"), index=False)

In [15]:
# check for inf and -inf values in wide file
wide_negative_inf_counts = (wide_cb_df == -float('inf')).sum()
print("Negative infinity counts in wide DataFrame:")
print(wide_negative_inf_counts)

Negative infinity counts in wide DataFrame:
primary_id            0
future_id             0
strategy_code         0
Year                  0
air_pollution         0
congestion            0
consumer_savings      0
crop_value            0
ecosystem_services    0
env_pollution         0
fuel_cost             0
human_health          0
ippu_value            0
land_pollution        0
lvst_value            0
road_safety           0
sector_specific       0
system_cost           0
technical_cost        0
technical_savings     0
water_pollution       0
dtype: int64